#!/bin/bash
# Build seed/country-base.sql.gz from the local dev MySQL container.
#
# This seed bootstraps a fresh country instance with:
#   - Complete table schema (all DDL)
#   - EAV attribute definitions, sets, and option values
#   - Directory data (countries, regions, currencies)
#   - Tax classes and standard rates
#   - Store/website/group structure (all 8 sites from SG kept for P5 simplicity)
#   - core_config_data (secrets stripped)
#   - Admin ACL groups (essential roles only, no user records)
#   - CMS pages and blocks (storefront layout)
#   - Category root and Default Category only (no SG course categories)
#   - Customer groups
#   - schema_migrations ledger (all current migrations pre-marked as applied)
#   - One seed admin user (password printed to stdout, MUST be changed)
#   - ZERO products, customers, orders, classes, enrolments, or secrets
#
# Usage:
#   ./scripts/provision/build-country-seed.sh
#
# Env overrides:
#   DB_CONTAINER   Docker container name (default: ai-mms-db_mysql-1)
#   MYSQL_USER     DB user (default: read from .env)
#   MYSQL_PASSWORD DB password (default: read from .env)
#   MYSQL_DATABASE DB name (default: read from .env)
#
# Output: seed/country-base.sql.gz (replaced if exists)
#
# Requirements: Docker running with the local dev MySQL container.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SEED_DIR="$REPO_ROOT/seed"
OUTPUT="$SEED_DIR/country-base.sql.gz"
MIGRATIONS_DIR="$REPO_ROOT/migrations"
TMP_DIR=$(mktemp -d)

cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

# --- Connection params ---
DB_CONTAINER="${DB_CONTAINER:-ai-mms-db_mysql-1}"

# Read from .env if not overridden
if [ -f "$REPO_ROOT/.env" ]; then
  set -a; source "$REPO_ROOT/.env"; set +a
fi

DB_USER="${MYSQL_USER:-magento}"
DB_PASS="${MYSQL_PASSWORD:?MYSQL_PASSWORD not set}"
DB_NAME="${MYSQL_DATABASE:?MYSQL_DATABASE not set}"

MY="docker exec -i $DB_CONTAINER mysql -u$DB_USER -p$DB_PASS $DB_NAME"
MD="docker exec -i $DB_CONTAINER mysqldump -u$DB_USER -p$DB_PASS --set-gtid-purged=OFF"

# safe_dump TABLE... — dump data for tables that actually exist in the source DB.
# Silently skips missing tables (some may have been removed in this installation).
safe_dump() {
  local existing=()
  for tbl in "$@"; do
    if $MY -e "SHOW TABLES LIKE '$tbl';" 2>/dev/null | grep -q .; then
      existing+=("$tbl")
    fi
  done
  if [ ${#existing[@]} -gt 0 ]; then
    $MD --no-create-info --compact --no-tablespaces "$DB_NAME" "${existing[@]}" 2>/dev/null
  fi
}

echo "=== build-country-seed.sh ==="
echo "Source container : $DB_CONTAINER"
echo "Source database  : $DB_NAME"
echo "Output           : $OUTPUT"
echo ""

# Verify container and DB are reachable
docker inspect "$DB_CONTAINER" > /dev/null 2>&1 \
  || { echo "ERROR: container $DB_CONTAINER not found"; exit 1; }
$MY -e "SELECT 1;" > /dev/null 2>/dev/null \
  || { echo "ERROR: cannot connect to $DB_NAME on $DB_CONTAINER"; exit 1; }

# --- Generate seed admin password ---
echo "Generating seed admin credentials..."
read SEED_PASS SEED_SALT SEED_HASH <<< $(python3 -c "
import secrets, hashlib
p = secrets.token_hex(8)
s = secrets.token_hex(1)
h = hashlib.sha256((s + p).encode()).hexdigest() + ':' + s
print(p, s, h)
")
SEED_ADMIN_EMAIL="admin@country-instance.local"
SEED_ADMIN_NAME="Seed Admin"
SEED_ADMIN_USERNAME="$SEED_ADMIN_EMAIL"

echo ""
echo "================================================================"
echo "  SEED ADMIN CREDENTIALS — record these before continuing"
echo "  Email    : $SEED_ADMIN_EMAIL"
echo "  Password : $SEED_PASS"
echo "  → Change this immediately after first login!"
echo "================================================================"
echo ""

# --- 0. Preamble ---
cat > "$TMP_DIR/0-preamble.sql" << 'ENDSQL'
-- Country seed — generated by scripts/provision/build-country-seed.sh
-- Import: mysql --init-command="SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO'" -u... < country-base.sql
-- OR via mysqldump-entrypoint (MySQL Docker auto-import) which sets the mode.

SET SESSION sql_mode = CONCAT(IF(@@sql_mode = '', '', CONCAT(@@sql_mode, ',')), 'NO_AUTO_VALUE_ON_ZERO');
SET NAMES utf8;
ENDSQL

# --- 1. Full table structure (DDL only, all tables) ---
echo "Dumping table structure..."
$MD \
  --no-data \
  --add-drop-table \
  --routines \
  --skip-triggers \
  --no-tablespaces \
  "$DB_NAME" \
  2>/dev/null > "$TMP_DIR/1-structure.sql"

# --- 2. Reference data — EAV metadata ---
echo "Dumping EAV reference data..."
safe_dump \
  eav_attribute eav_attribute_group eav_attribute_label eav_attribute_option \
  eav_attribute_option_swatch eav_attribute_option_value eav_attribute_set \
  eav_entity eav_entity_attribute eav_entity_store eav_entity_type \
  eav_form_element eav_form_fieldset eav_form_fieldset_element \
  eav_form_type eav_form_type_entity \
  catalog_eav_attribute customer_eav_attribute customer_eav_attribute_website \
  > "$TMP_DIR/2-eav.sql"

# --- 3. Reference data — directory (countries, regions, currencies) ---
echo "Dumping directory reference data..."
safe_dump \
  directory_country directory_country_format directory_country_region \
  directory_country_region_name directory_currency_rate \
  > "$TMP_DIR/3-directory.sql"

# --- 4. Reference data — tax (may be absent in this install — GST is custom) ---
echo "Dumping tax reference data..."
safe_dump \
  tax_class tax_calculation tax_calculation_rate tax_calculation_rule \
  > "$TMP_DIR/4-tax.sql"

# --- 5. Reference data — customer groups ---
echo "Dumping customer groups..."
safe_dump customer_group > "$TMP_DIR/5-customer-groups.sql"

# --- 6. Store/website/group structure + module version registry ---
echo "Dumping store configuration..."
safe_dump core_website core_store_group core_store > "$TMP_DIR/6-stores.sql"

# core_resource: Magento's module setup version table.
# Without this, every module installer fires on first request and 503s
# because the tables already exist but Magento doesn't know they're installed.
echo "Dumping core_resource (module setup versions)..."
safe_dump core_resource >> "$TMP_DIR/6-stores.sql"

# --- 7. core_config_data — dump only NON-secret rows at export time ---
# Filter here so no secret ever lands in the seed file (even temporarily).
echo "Dumping core_config_data (secrets excluded)..."
$MD --no-create-info --compact --no-tablespaces \
  --where "path NOT LIKE 'smtppro/%'
    AND path NOT LIKE '%oauth%'
    AND path NOT LIKE '%gmail%'
    AND path NOT LIKE '%client_secret%'
    AND path NOT LIKE '%api_key%'
    AND path NOT LIKE '%api_secret%'
    AND path NOT LIKE 'mmd/trainer_import/%'
    AND path NOT LIKE 'mmd/course_sync/%'
    AND path NOT LIKE 'courses/general/%'
    AND path NOT LIKE 'mmd_marketing/%'
    AND path NOT LIKE 'payment/%/login'
    AND path NOT LIKE 'payment/%/password'
    AND path NOT LIKE 'payment/%/signature'
    AND path NOT LIKE 'payment/%/token'
    AND path NOT LIKE 'payment/%/client_id'
    AND path NOT LIKE '%/private_key%'
    AND path NOT LIKE '%/publishable_key%'
    AND path NOT LIKE '%/stripe/%'
    AND path NOT LIKE '%hitpay%'
    AND path NOT LIKE 'mmd/class_formation/%'
    AND path NOT LIKE 'mmd/backfill%'
    AND path NOT LIKE 'anthropic%'
    AND path NOT LIKE '%r2_%'
    AND path NOT LIKE '%cloudflare%'
    AND path NOT LIKE '%s3_%'
    AND path NOT LIKE 'google/%'
    AND path NOT LIKE '%turnstile%'
    AND path NOT LIKE '%recaptcha%'
    AND path NOT LIKE '%mailerlite%'
    AND path NOT IN ('web/unsecure/base_url','web/secure/base_url')" \
  "$DB_NAME" core_config_data \
  2>/dev/null > "$TMP_DIR/7-config.sql"

# --- 8. Admin ACL groups and rules ---
echo "Dumping admin ACL groups..."
safe_dump admin_role admin_rule > "$TMP_DIR/8-acl.sql"

# --- 9. CMS pages and blocks (storefront layout) ---
echo "Dumping CMS pages and blocks..."
safe_dump cms_block cms_block_store cms_page cms_page_store > "$TMP_DIR/9-cms.sql"

# --- 10. Category root and Default Category only ---
echo "Dumping root categories..."
$MD --no-create-info --compact --no-tablespaces \
  --where "level <= 1" \
  "$DB_NAME" catalog_category_entity \
  2>/dev/null > "$TMP_DIR/10-cat-entity.sql"

# Category EAV values for root (entity_id=1) and Default Category (entity_id=2) only
for tbl in catalog_category_entity_datetime catalog_category_entity_decimal \
           catalog_category_entity_int catalog_category_entity_text \
           catalog_category_entity_varchar; do
  if $MY -e "SHOW TABLES LIKE '$tbl';" 2>/dev/null | grep -q .; then
    $MD --no-create-info --compact --no-tablespaces \
      --where "entity_id IN (1,2)" \
      "$DB_NAME" "$tbl" \
      2>/dev/null >> "$TMP_DIR/10-cat-entity.sql"
  fi
done

# --- 11. Cleanup — sanitize secrets, strip business data, insert seed admin ---
echo "Generating cleanup SQL..."

# Build schema_migrations INSERT VALUES from current migration files
MIGRATION_VALUES=""
while IFS= read -r f; do
  [ -n "$MIGRATION_VALUES" ] && MIGRATION_VALUES="${MIGRATION_VALUES},"
  MIGRATION_VALUES="${MIGRATION_VALUES}('$(basename "$f")', NOW())"
done < <(ls "$MIGRATIONS_DIR"/*.sql 2>/dev/null)

cat > "$TMP_DIR/11-cleanup.sql" << ENDSQL
-- ================================================================
-- CLEANUP: reset base URLs, strip business data, apply seed state
-- Secrets were excluded at dump time (see build-country-seed.sh).
-- ================================================================
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------------------------------------------
-- 1. Reset base URLs to placeholder (entrypoint sets real URL from env)
-- ----------------------------------------------------------------
DELETE FROM core_config_data WHERE path IN ('web/unsecure/base_url','web/secure/base_url');
INSERT INTO core_config_data (scope, scope_id, path, value) VALUES
  ('default', 0, 'web/unsecure/base_url', 'http://placeholder.local/'),
  ('default', 0, 'web/secure/base_url',   'https://placeholder.local/')
ON DUPLICATE KEY UPDATE value = VALUES(value);
-- Per-store/website base URL overrides — clear so global default is used
DELETE FROM core_config_data WHERE path IN ('web/unsecure/base_url','web/secure/base_url')
  AND scope IN ('websites','stores');

-- Disable Magento URL validation (causes 500s when base URL changes)
DELETE FROM core_config_data WHERE path = 'web/url/use_store';

-- ----------------------------------------------------------------
-- 3. Strip business data
-- ----------------------------------------------------------------
-- Products (all)
DELETE FROM catalog_product_entity;
DELETE FROM cataloginventory_stock_item;
DELETE FROM cataloginventory_stock_status;

-- Categories: remove all except root (entity_id=1) and Default Category (entity_id=2)
DELETE FROM catalog_category_entity WHERE entity_id NOT IN (1,2);
DELETE FROM catalog_category_entity_datetime WHERE entity_id NOT IN (1,2);
DELETE FROM catalog_category_entity_decimal WHERE entity_id NOT IN (1,2);
DELETE FROM catalog_category_entity_int WHERE entity_id NOT IN (1,2);
DELETE FROM catalog_category_entity_text WHERE entity_id NOT IN (1,2);
DELETE FROM catalog_category_entity_varchar WHERE entity_id NOT IN (1,2);
DELETE FROM catalog_category_product;
DELETE FROM catalog_category_product_index;

-- Customers
DELETE FROM customer_entity;

-- Orders and registrations
DELETE FROM sales_flat_order;

-- Classes and enrolments
DELETE FROM course_runs;
DELETE FROM course_run_enrolments;
DELETE FROM course_run_registry;
DELETE FROM course_run_trainer_invitations;

-- MMD operational tables (no business data in fresh instance)
DELETE FROM mmd_lead;
DELETE FROM mmd_order_entity_custom;
DELETE FROM mmd_feedback_form_response;
DELETE FROM mmd_trainer_import_log;
DELETE FROM mmd_class_id_map;
DELETE FROM mmd_audit_issues;
DELETE FROM mmd_customer_entity_data;
DELETE FROM mmd_product_trainer;

-- Admin users and role assignments
DELETE FROM admin_user;
DELETE FROM mmd_user_role_map;

-- ----------------------------------------------------------------
-- 4. Admin ACL — keep essential role groups only
--    Essential: 1=Administrators, plus MMD_RoleManager canonical roles
-- ----------------------------------------------------------------
-- Remove SG-specific groups and user role assignments
DELETE FROM admin_role WHERE role_type = 'U';
DELETE FROM admin_role WHERE role_type = 'G'
  AND role_id NOT IN (1, 256, 257, 258, 259, 260, 261, 263);
DELETE FROM admin_rule WHERE role_id NOT IN (1, 256, 257, 258, 259, 260, 261, 263);

-- ----------------------------------------------------------------
-- 5. Insert seed admin user
--    Password: printed by build-country-seed.sh — CHANGE AFTER FIRST LOGIN
-- ----------------------------------------------------------------
INSERT INTO admin_user
  (firstname, lastname, username, email, password, is_active, reload_acl_flag)
VALUES
  ('Seed', 'Admin', '$SEED_ADMIN_EMAIL', '$SEED_ADMIN_EMAIL', '$SEED_HASH', 1, 0);

-- Assign seed admin to Administrators group (role_id=1)
SET @seed_user_id = LAST_INSERT_ID();
INSERT INTO admin_role (parent_id, tree_level, sort_order, role_type, user_id, role_name)
VALUES (1, 2, 0, 'U', @seed_user_id, '$SEED_ADMIN_NAME');

-- ----------------------------------------------------------------
-- 6. schema_migrations ledger — mark ALL current migrations as applied
--    so apply.php skips them on first boot (schema is already in the dump)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
  filename   VARCHAR(255) NOT NULL PRIMARY KEY,
  applied_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT IGNORE INTO schema_migrations (filename, applied_at) VALUES
$MIGRATION_VALUES;

SET FOREIGN_KEY_CHECKS = 1;

-- ================================================================
-- END OF SEED
-- ================================================================
ENDSQL

# --- Combine all parts ---
echo "Combining and compressing..."
mkdir -p "$SEED_DIR"

{
  cat "$TMP_DIR/0-preamble.sql"
  cat "$TMP_DIR/1-structure.sql"
  echo "-- ============================================================"
  echo "-- REFERENCE DATA"
  echo "-- ============================================================"
  echo "SET FOREIGN_KEY_CHECKS = 0;"
  cat "$TMP_DIR/2-eav.sql"
  cat "$TMP_DIR/3-directory.sql"
  cat "$TMP_DIR/4-tax.sql"
  cat "$TMP_DIR/5-customer-groups.sql"
  cat "$TMP_DIR/6-stores.sql"
  cat "$TMP_DIR/7-config.sql"
  cat "$TMP_DIR/8-acl.sql"
  cat "$TMP_DIR/9-cms.sql"
  cat "$TMP_DIR/10-cat-entity.sql"
  echo "SET FOREIGN_KEY_CHECKS = 1;"
  cat "$TMP_DIR/11-cleanup.sql"
} | gzip -9 > "$OUTPUT"

echo ""
echo "Seed written: $OUTPUT ($(du -sh "$OUTPUT" | cut -f1))"

# --- Assertions ---
echo ""
echo "Running assertions against source DB..."
PASS=0
FAIL=0

assert_zero() {
  local label="$1"
  local query="$2"
  local count
  count=$($MY -sN -e "$query" 2>/dev/null)
  if [ "$count" = "0" ]; then
    echo "  OK   : $label"
    PASS=$((PASS + 1))
  else
    echo "  FAIL : $label — expected 0 rows, got $count"
    FAIL=$((FAIL + 1))
  fi
}

assert_nonzero() {
  local label="$1"
  local query="$2"
  local count
  count=$($MY -sN -e "$query" 2>/dev/null)
  if [ "$count" -gt 0 ] 2>/dev/null; then
    echo "  OK   : $label ($count rows)"
    PASS=$((PASS + 1))
  else
    echo "  FAIL : $label — expected rows, got 0"
    FAIL=$((FAIL + 1))
  fi
}

# Verify source has the reference data we're including
assert_nonzero "eav_attribute has rows"       "SELECT COUNT(*) FROM eav_attribute"
assert_nonzero "directory_country has rows"   "SELECT COUNT(*) FROM directory_country"
assert_nonzero "core_store has rows"          "SELECT COUNT(*) FROM core_store"
assert_nonzero "admin_role has Administrators" "SELECT COUNT(*) FROM admin_role WHERE role_id=1 AND role_type='G'"

# Verify seed SQL doesn't contain known secret strings (grep uncompressed)
echo ""
echo "Scanning seed for known secret patterns..."
TMPUNZIP="$TMP_DIR/check.sql"
gunzip -c "$OUTPUT" > "$TMPUNZIP"

check_absent() {
  local label="$1"
  local pattern="$2"
  if grep -qi "$pattern" "$TMPUNZIP" 2>/dev/null; then
    echo "  FAIL : seed contains pattern: $label"
    FAIL=$((FAIL + 1))
  else
    echo "  OK   : seed does not contain: $label"
    PASS=$((PASS + 1))
  fi
}

# Check for specific SECRET CREDENTIAL paths, not module names.
# admin_rule rows legitimately reference module routes like 'admin/system/config/smtppro'
# which is NOT a credential. We check for the core_config_data INSERT path format.
check_absent "SMTP password row"       "smtppro/general/googleapps_gpassword"
check_absent "SMTP email row"          "smtppro/general/googleapps_email"
check_absent "HitPay API key row"      "payment/hitpay/api_key"
check_absent "HitPay salt row"         "payment/hitpay/salt"
check_absent "MailerLite key row"      "mmd_marketing/api/mailerlite_key"
check_absent "Anthropic key format"    "sk-ant-"
check_absent "Stripe API key row"      "stripe/general/stripe_api_key"
check_absent "R2 secret key row"       "R2_SECRET_ACCESS_KEY"
check_absent "OAuth client secret row" "client_secret.*value"

# Verify seed has essential tables/data
check_present() {
  local label="$1"
  local pattern="$2"
  if grep -qi "$pattern" "$TMPUNZIP" 2>/dev/null; then
    echo "  OK   : seed contains: $label"
    PASS=$((PASS + 1))
  else
    echo "  FAIL : seed missing: $label"
    FAIL=$((FAIL + 1))
  fi
}

check_present "core_resource inserts"      "INSERT.*core_resource"
check_present "schema_migrations table"    "CREATE TABLE.*schema_migrations"
check_present "schema_migrations inserts"  "INSERT.*schema_migrations"
check_present "eav_attribute inserts"      "INSERT.*eav_attribute"
check_present "directory_country inserts"  "INSERT.*directory_country"
check_present "core_store inserts"         "INSERT.*core_store"
check_present "placeholder base URL"       "placeholder.local"
check_present "seed admin user"            "$SEED_ADMIN_EMAIL"

echo ""
echo "=== Assertions: $PASS passed, $FAIL failed ==="

if [ "$FAIL" -gt 0 ]; then
  echo "SEED BUILD FAILED — $FAIL assertion(s) failed. Fix and rebuild."
  exit 1
fi

echo ""
echo "==================================================================="
echo "  Seed build SUCCESSFUL"
echo "  Output: $OUTPUT"
echo ""
echo "  REMINDER: the seed admin password is:"
echo "  Email    : $SEED_ADMIN_EMAIL"
echo "  Password : $SEED_PASS"
echo "  Store it in your password manager NOW."
echo "  Then change it after first login at /tigerdragon/admin/user/edit/"
echo "==================================================================="
