-- Cancel synthetic seed / enrol-script orders.
--
-- SEED-* and ENROL-* increment_ids are generated by local test
-- fixtures (SEED-CURR-N / SEED-UPC-N / SEED-PAST-N for current /
-- upcoming / past class buckets, ENROL-<ts>-<hash> for the seed
-- enrolment script). They shouldn't appear as live enrolments on
-- production — admin testers logged in as those accounts kept seeing
-- them on the Learner My Classes view.
--
-- We cancel (state='canceled') rather than delete so the audit trail
-- is preserved and Magento's order lifecycle stays consistent. The
-- Learner view filters `state NOT IN ('canceled','closed')`, so these
-- rows immediately drop out of My Classes after this runs.
--
-- Idempotent — re-runs do nothing because the WHERE clause excludes
-- already-canceled rows.

UPDATE sales_flat_order
   SET state = 'canceled', status = 'canceled'
 WHERE (increment_id LIKE 'SEED-%' OR increment_id LIKE 'ENROL-%')
   AND state <> 'canceled';

UPDATE sales_flat_order_grid
   SET status = 'canceled'
 WHERE (increment_id LIKE 'SEED-%' OR increment_id LIKE 'ENROL-%')
   AND status <> 'canceled';
