-- C947: rename "Design and Process Failure Mode Effect Analysis (DPFMEA) Masterclass"
-- -> "FMEA Masterclass", and move the slug design-process-fmea -> fmea-masterclass
-- with a permanent (301) redirect from every stored old path.
--
-- SG-only course (C-prefix). Guarded on the SG store so this is a no-op on the
-- MY/GH partner servers, which run the same migration chain.
-- Idempotent: safe to re-run.

SET @sg  := (SELECT COUNT(*) FROM core_store WHERE store_id = 1 AND code = 'singapore');
SET @pid := (SELECT entity_id FROM catalog_product_entity WHERE sku = 'C947');

-- ---------------------------------------------------------------- name ----
SET @a_name := (SELECT attribute_id FROM eav_attribute a
                JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'name');

UPDATE catalog_product_entity_varchar
SET value = 'FMEA Masterclass'
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_name;

-- ------------------------------------------------------------ url_key ----
SET @a_urlkey := (SELECT attribute_id FROM eav_attribute a
                  JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                  WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'url_key');

UPDATE catalog_product_entity_varchar
SET value = 'fmea-masterclass'
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_urlkey;

-- url_path is regenerated by the Catalog URL Rewrites indexer, but keep the
-- stored value consistent so a pre-reindex read is not stale.
SET @a_urlpath := (SELECT attribute_id FROM eav_attribute a
                   JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                   WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'url_path');

UPDATE catalog_product_entity_varchar
SET value = 'fmea-masterclass.html'
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_urlpath;

-- ------------------------------------------------------ image labels -----
-- The alt text still named the old course.
SET @a_imglbl  := (SELECT attribute_id FROM eav_attribute a
                   JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                   WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'image_label');
SET @a_simglbl := (SELECT attribute_id FROM eav_attribute a
                   JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                   WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'small_image_label');

UPDATE catalog_product_entity_varchar
SET value = 'FMEA Masterclass Course'
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id IN (@a_imglbl, @a_simglbl);

-- --------------------------------------------------------- meta data -----
SET @a_mtitle := (SELECT attribute_id FROM eav_attribute a
                  JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                  WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'meta_title');

-- meta_title/meta_description are varchar(255); both fit well inside that.
UPDATE catalog_product_entity_varchar
SET value = 'FMEA Masterclass: Design & Process Failure Mode Effect Analysis | Tertiary Courses Singapore'
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_mtitle;

-- ------------------------------------------------------- 301 rewrites ----
-- Every stored path that resolved to the old slug must 301 to the new bare
-- slug. options='RP' IS the 301; an empty options column is a 302 and does not
-- transfer ranking.
--
-- 1) Repoint the existing RP rows whose TARGET was an old-slug path.
UPDATE core_url_rewrite
SET target_path = 'fmea-masterclass.html', options = 'RP', is_system = 0
WHERE @sg = 1
  AND options = 'RP'
  AND target_path LIKE '%design-process-fmea.html';

-- 2) Turn the old SYSTEM rows (the ones that used to serve the product) into
--    permanent redirects to the new bare slug. The indexer will recreate the
--    system rows for the new slug.
UPDATE core_url_rewrite
SET target_path = 'fmea-masterclass.html', options = 'RP', is_system = 0
WHERE @sg = 1 AND @pid IS NOT NULL
  AND product_id = @pid
  AND request_path LIKE '%design-process-fmea.html'
  AND target_path LIKE 'catalog/product/view/id/%';

-- 3) Belt and braces: ensure a bare old-slug -> new-slug row exists in both
--    the default (0) and SG (1) scopes even if the rows above were missing.
INSERT IGNORE INTO core_url_rewrite
  (store_id, id_path, request_path, target_path, is_system, options)
SELECT s.store_id,
       CONCAT('manual-301-', MD5('design-process-fmea.html'), '-', s.store_id),
       'design-process-fmea.html', 'fmea-masterclass.html', 0, 'RP'
FROM (SELECT 0 AS store_id UNION ALL SELECT 1 AS store_id) s
WHERE @sg = 1
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT * FROM core_url_rewrite) x
    WHERE x.request_path = 'design-process-fmea.html' AND x.store_id = s.store_id
  );

-- ------------------------------------------------- search redirects ------
-- Point stored search redirects straight at the new URL (one hop, not two).
UPDATE catalogsearch_query
SET redirect = REPLACE(redirect, 'design-process-fmea.html', 'fmea-masterclass.html')
WHERE @sg = 1
  AND redirect LIKE '%design-process-fmea.html';
