-- Migration 154: move 'AWS Skill Builder' section out of short_description
-- and into additional_note for every AWS course that carries it.
--
-- Mirrors what scripts/local-dev/move-aws-skill-builder-to-additional-note.php
-- already did on local. Backup payloads come from
-- media/migrations-reports/move-aws-skill-builder-apply-20260525-043423.json
-- (24 products). Each statement is idempotent — REPLACE() no-ops on
-- already-stripped rows, and the additional_note UPDATE is guarded by
-- NOT LIKE so a re-run on already-appended values is a no-op.

-- C1041 (entity_id=1041)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1041 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1041 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1041, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1041 AND attribute_id = 158 AND store_id = 0);

-- C1330 (entity_id=1330)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1330 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1330 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1330, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1330 AND attribute_id = 158 AND store_id = 0);

-- C1331 (entity_id=1331)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1331 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1331 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1331, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1331 AND attribute_id = 158 AND store_id = 0);

-- C1391 (entity_id=1391)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1391 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1391 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1391, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1391 AND attribute_id = 158 AND store_id = 0);

-- C1392 (entity_id=1392)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1392 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1392 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1392, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1392 AND attribute_id = 158 AND store_id = 0);

-- C1393 (entity_id=1393)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1393 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1393 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1393, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1393 AND attribute_id = 158 AND store_id = 0);

-- C1407 (entity_id=1407)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1407 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1407 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1407, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1407 AND attribute_id = 158 AND store_id = 0);

-- C19 (entity_id=19)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 19 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 19 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 19, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 19 AND attribute_id = 158 AND store_id = 0);

-- C196 (entity_id=196)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 196 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 196 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 196, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 196 AND attribute_id = 158 AND store_id = 0);

-- C279 (entity_id=279)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 279 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 279 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 279, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 279 AND attribute_id = 158 AND store_id = 0);

-- C371 (entity_id=371)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 371 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 371 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 371, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 371 AND attribute_id = 158 AND store_id = 0);

-- C635 (entity_id=635)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 635 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 635 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 635, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 635 AND attribute_id = 158 AND store_id = 0);

-- TGS-2023039183 (entity_id=617)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest <span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 617 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest <span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 617 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 617, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest <span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 617 AND attribute_id = 158 AND store_id = 0);

-- TGS-2023040474 (entity_id=1307)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1307 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1307 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1307, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1307 AND attribute_id = 158 AND store_id = 0);

-- TGS-2024048315 (entity_id=323)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 323 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 323 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 323, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 323 AND attribute_id = 158 AND store_id = 0);

-- TGS-2024049338 (entity_id=537)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 537 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 537 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 537, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 537 AND attribute_id = 158 AND store_id = 0);

-- TGS-2024049340 (entity_id=1326)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1326 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1326 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1326, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1326 AND attribute_id = 158 AND store_id = 0);

-- TGS-2024051413 (entity_id=648)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 648 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 648 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 648, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 648 AND attribute_id = 158 AND store_id = 0);

-- TGS-2025052675 (entity_id=1315)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1315 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1315 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1315, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1315 AND attribute_id = 158 AND store_id = 0);

-- TGS-2025053926 (entity_id=555)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 555 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 555 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 555, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 555 AND attribute_id = 158 AND store_id = 0);

-- TGS-2025054815 (entity_id=1856)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1856 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1856 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1856, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1856 AND attribute_id = 158 AND store_id = 0);

-- TGS-2025059025 (entity_id=1861)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>\r\n', '') WHERE entity_id = 1861 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>') WHERE entity_id = 1861 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1861, '<p>We are authorised AWS reseller of AWS Skill Builder. If you would like to subscribe to AWS Skill Builder, please register you interest&nbsp;<span style=\"text-decoration: underline;\"><a href=\"https://www.tertiarycourses.com.sg/aws-skill-builder-individual-yearly-subscription.html\" title=\"AWS Skills Builder\" target=\"_blank\">here</a></span>.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1861 AND attribute_id = 158 AND store_id = 0);

-- V011 (entity_id=1633)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you have attended any of our AWS training before, we will offer 10% discount for your AWS Skill Builder subscription.</p>', '') WHERE entity_id = 1633 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you have attended any of our AWS training before, we will offer 10% discount for your AWS Skill Builder subscription.</p>') WHERE entity_id = 1633 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1633, '<p>We are authorised AWS reseller of AWS Skill Builder. If you have attended any of our AWS training before, we will offer 10% discount for your AWS Skill Builder subscription.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1633 AND attribute_id = 158 AND store_id = 0);

-- V012 (entity_id=1634)
UPDATE catalog_product_entity_text SET value = REPLACE(value, '<h2>AWS Skill Builder</h2>\r\n<p>We are authorised AWS reseller of AWS Skill Builder. If you have attended any of our AWS training before, we will offer 10% discount for your AWS Skill Builder subscription.</p>', '') WHERE entity_id = 1634 AND attribute_id = 73;
UPDATE catalog_product_entity_text SET value = CONCAT(value, '\n\n<p>We are authorised AWS reseller of AWS Skill Builder. If you have attended any of our AWS training before, we will offer 10% discount for your AWS Skill Builder subscription.</p>') WHERE entity_id = 1634 AND attribute_id = 158 AND store_id = 0 AND value NOT LIKE '%AWS Skill Builder%';
INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 158, 0, 1634, '<p>We are authorised AWS reseller of AWS Skill Builder. If you have attended any of our AWS training before, we will offer 10% discount for your AWS Skill Builder subscription.</p>' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM catalog_product_entity_text                   WHERE entity_id = 1634 AND attribute_id = 158 AND store_id = 0);
