-- Anonymise the three Claude Code corporate training case studies.
-- Old article URLs retain permanent redirects; neutral hero and class-photo
-- assets were rendered/inspected and uploaded before this migration.
-- Keep this correction scoped to the Singapore instance and to the three slugs.
SET @is_sg := IF(@mms_instance = 'SG', 1, 0);

-- IT support ticketing app (this post was created through the blog admin).
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/uob-agentic-ai-claude-code-class-20260901.jpg', 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/financial-company-support-class-20260901.jpg') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'UOB', 'financial company') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'class directly to financial company.', 'class for a financial company.') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, '24 financial company IT support staff', '24 IT support staff from a financial company') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'held at financial company premises', 'held at the company&rsquo;s premises') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'held on-site at financial company.', 'held on-site at the company&rsquo;s premises.') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'What the financial company team took away', 'What the team took away') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'like it was for financial company?', 'like it was for a financial company?') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'for financial company&rsquo;s IT support team', 'for the financial company&rsquo;s IT support team') WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `title` = 'Inside a Financial Company''s Agentic AI Class: IT Support', `excerpt` = 'Twenty-four IT support staff at a financial company built a ticketing app with Claude Code and explored commands, MCP tools, skills, agents and hooks.', `meta_title` = 'Claude Code IT Support Training | Financial Company', `meta_description` = 'How 24 IT support staff at a financial company built a ticketing app with Claude Code in one on-site class.', `meta_keywords` = REPLACE(`meta_keywords`, 'UOB', 'financial company'), `hero_image_url` = IF(`hero_image_url` IS NULL OR `hero_image_url` = '' OR `hero_image_url` LIKE '%/blog/auto-%' OR `hero_image_url` LIKE '%uob%', 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/auto-20260925-financial-company-support.png', `hero_image_url`), `updated_at` = NOW() WHERE `url_key` IN ('uob-agentic-ai-claude-code-it-support-ticketing-app', 'financial-company-agentic-ai-claude-code-it-support-ticketing-app') AND @is_sg = 1;

-- PMO Kanban board.
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/uob-pmo-kanban-claude-code-20260908.jpg', 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/financial-company-pmo-class-20260908.jpg') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'UOB', 'financial company') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'from financial company&rsquo;s infrastructure and development teams, at financial company&rsquo;s Punggol Campus &mdash; financial company Tower 80', 'from a financial company&rsquo;s infrastructure and development teams, at the company&rsquo;s training venue') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, '20 engineers from financial company infrastructure', '20 engineers from a financial company&rsquo;s infrastructure') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, '20 engineers from financial company&rsquo;s infrastructure', '20 engineers from a financial company&rsquo;s infrastructure') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'held on-site at financial company Tower 80, Punggol Campus', 'held on-site at the company&rsquo;s training venue') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'as this financial company cohort did', 'as this cohort did') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'A previous financial company group', 'A previous group') WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `title` = 'PMO Kanban Board with Claude Code: Financial Company Case Study', `excerpt` = 'Twenty engineers from a financial company built a PMO Kanban board with Claude Code, including WIP limits, an audit trail and cycle-time reporting.', `meta_title` = 'PMO Kanban Board with Claude Code | Financial Company', `meta_description` = 'See how 20 engineers at a financial company built a PMO Kanban board with Claude Code and applied five agentic AI practices.', `meta_keywords` = REPLACE(`meta_keywords`, 'UOB', 'financial company'), `hero_image_url` = IF(`hero_image_url` IS NULL OR `hero_image_url` = '' OR `hero_image_url` LIKE '%/blog/auto-%' OR `hero_image_url` LIKE '%uob%', 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/auto-20260925-financial-company-pmo.png', `hero_image_url`), `updated_at` = NOW() WHERE `url_key` IN ('uob-pmo-kanban-board-claude-code-corporate-training', 'financial-company-pmo-kanban-board-claude-code-corporate-training') AND @is_sg = 1;

-- IT operations and AI agent trigger model.
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/uob-agentic-ai-claude-code-20260916.jpg', 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/financial-company-operations-class-20260916.jpg') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'UOB', 'financial company') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'for financial company &mdash;', 'for a financial company &mdash;') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, '22 financial company IT operations staff', '22 IT operations staff from a financial company') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'staff from financial company at', 'staff from a financial company at') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'third financial company cohort', 'third cohort from the financial company') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'three financial company cohorts', 'three cohorts from the financial company') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `content` = REPLACE(`content`, 'Each financial company cohort', 'Each cohort') WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `title` = 'Five Ways to Trigger an AI Agent: Financial Company Case Study', `excerpt` = 'Twenty-two IT operations staff at a financial company explored the agentic loop and five ways to trigger Claude Code: memory, skills, hooks, commands and subagents.', `meta_title` = 'AI Agent Trigger Models | Financial Company IT Operations', `meta_description` = 'How 22 IT operations staff at a financial company explored the agentic loop and five Claude Code trigger mechanisms.', `meta_keywords` = REPLACE(`meta_keywords`, 'UOB', 'financial company'), `hero_image_url` = IF(`hero_image_url` IS NULL OR `hero_image_url` = '' OR `hero_image_url` LIKE '%/blog/auto-%' OR `hero_image_url` LIKE '%uob%', 'https://pub-77c0dec029944b0386e40673ce81081f.r2.dev/blog/auto-20260925-financial-company-operations.png', `hero_image_url`), `updated_at` = NOW() WHERE `url_key` IN ('uob-agentic-ai-claude-code-trigger-model-it-operations', 'financial-company-agentic-ai-claude-code-trigger-model-it-operations') AND @is_sg = 1;

-- Create redirects while the old slugs still identify the rows.
INSERT INTO `core_url_rewrite` (`store_id`, `id_path`, `request_path`, `target_path`, `is_system`, `options`) SELECT 1, CONCAT('mmd_blog_post/', `post_id`, '/financial-company-anonymisation'), 'blog/uob-agentic-ai-claude-code-it-support-ticketing-app', 'blog/financial-company-agentic-ai-claude-code-it-support-ticketing-app', 0, 'RP' FROM `mmd_blog_post` WHERE `url_key` = 'uob-agentic-ai-claude-code-it-support-ticketing-app' AND @is_sg = 1 ON DUPLICATE KEY UPDATE `target_path` = VALUES(`target_path`), `options` = VALUES(`options`);
INSERT INTO `core_url_rewrite` (`store_id`, `id_path`, `request_path`, `target_path`, `is_system`, `options`) SELECT 1, CONCAT('mmd_blog_post/', `post_id`, '/financial-company-anonymisation'), 'blog/uob-pmo-kanban-board-claude-code-corporate-training', 'blog/financial-company-pmo-kanban-board-claude-code-corporate-training', 0, 'RP' FROM `mmd_blog_post` WHERE `url_key` = 'uob-pmo-kanban-board-claude-code-corporate-training' AND @is_sg = 1 ON DUPLICATE KEY UPDATE `target_path` = VALUES(`target_path`), `options` = VALUES(`options`);
INSERT INTO `core_url_rewrite` (`store_id`, `id_path`, `request_path`, `target_path`, `is_system`, `options`) SELECT 1, CONCAT('mmd_blog_post/', `post_id`, '/financial-company-anonymisation'), 'blog/uob-agentic-ai-claude-code-trigger-model-it-operations', 'blog/financial-company-agentic-ai-claude-code-trigger-model-it-operations', 0, 'RP' FROM `mmd_blog_post` WHERE `url_key` = 'uob-agentic-ai-claude-code-trigger-model-it-operations' AND @is_sg = 1 ON DUPLICATE KEY UPDATE `target_path` = VALUES(`target_path`), `options` = VALUES(`options`);

UPDATE `mmd_blog_post` SET `url_key` = 'financial-company-agentic-ai-claude-code-it-support-ticketing-app' WHERE `url_key` = 'uob-agentic-ai-claude-code-it-support-ticketing-app' AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `url_key` = 'financial-company-pmo-kanban-board-claude-code-corporate-training' WHERE `url_key` = 'uob-pmo-kanban-board-claude-code-corporate-training' AND @is_sg = 1;
UPDATE `mmd_blog_post` SET `url_key` = 'financial-company-agentic-ai-claude-code-trigger-model-it-operations' WHERE `url_key` = 'uob-agentic-ai-claude-code-trigger-model-it-operations' AND @is_sg = 1;
