-- 191: Add "most sensible" redirects for search terms whose curated redirect was
-- dropped in migration 189 (their old target was dead/corrupted).
--
-- Policy (per request): a search term should never dead-end. Preference order is
-- product page > flat category page > homepage > empty (let Magento search).
-- These dropped terms are overwhelmingly TOPIC-level ("blockchain", "tableau",
-- "arduino", "photoshop"), so the correct tier for them is the flat CATEGORY
-- page; product-level intent was already covered by the 189 restore. Each term
-- is matched (search text + old slug, stopword-filtered token overlap) to the
-- best CURRENT active category, and the target was validated to return HTTP 200
-- ON THAT STORE'S OWN DOMAIN (SG term -> com.sg, MY -> com.my, GH -> com.gh,
-- BT -> tertiarycourses.bt). Terms with no confident match are left WITHOUT a
-- redirect on purpose -> Magento search shows relevant courses (the "empty" tier).
--
-- Store-scoped, idempotent temp-table UPDATE + INSERT-missing. Re-running is a
-- no-op. Does not touch the 189-restored redirects (these are dropped terms only).

DROP TEMPORARY TABLE IF EXISTS _sensible_redirects;
CREATE TEMPORARY TABLE _sensible_redirects (
  query_text VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  store_id SMALLINT UNSIGNED NOT NULL,
  redirect VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO _sensible_redirects (query_text, store_id, redirect) VALUES
('3d design',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('3d design and printing',1,'https://www.tertiarycourses.com.sg/3d-printing-training-courses.html'),
('3D printing',1,'https://www.tertiarycourses.com.sg/3d-printing-training-courses.html'),
('3ds Max Certified Professional Certificate Preparation and Exam Voucher',1,'https://www.tertiarycourses.com.sg/autodesk-3ds-max-trainings.html'),
('accounting xero',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('acounting xero',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('additiive manufacturing',1,'https://www.tertiarycourses.com.sg/logistics-and-manufacturing-courses.html'),
('adobe',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('adobe animate',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('adobe animate cc',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('ADOBE ANIMATE CC TRAINING',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('Adobe certification',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('Adobe Certified Associate (ACA) Exam Voucher',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('adobe photoshop',1,'https://www.tertiarycourses.com.sg/adobe-photoshop-courses.html'),
('adobe software training',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('Advance arduino',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Advance arduino course',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('advance blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Advance Google',1,'https://www.tertiarycourses.com.sg/google-software-training-in.html'),
('advanced 3d max',1,'https://www.tertiarycourses.com.sg/autodesk-3ds-max-trainings.html'),
('advanced 3ds max',1,'https://www.tertiarycourses.com.sg/autodesk-3ds-max-trainings.html'),
('Advanced 3DS MAX for Architectural Visualization',1,'https://www.tertiarycourses.com.sg/autodesk-3ds-max-trainings.html'),
('advanced adobe CC',1,'https://www.tertiarycourses.com.sg/adobe-software-training-in.html'),
('advanced arduino',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('advanced arduino essential',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Advanced Arduino Training',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Advanced blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Advanced Blockchain Applications with Solidity',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Advanced c',1,'https://www.tertiarycourses.com.sg/c-cplusplus-csharp-training-in.html'),
('advanced communication',1,'https://www.tertiarycourses.com.sg/communication-courses.html'),
('Advanced CSS3 Animation Training',1,'https://www.tertiarycourses.com.sg/gaming-animation-and-video-courses-in.html'),
('advanced ethereum',1,'https://www.tertiarycourses.com.sg/ethereum-skillsfuture-courses-in.html'),
('Advanced Ethereum Blockchain DApp Development',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('advanced google',1,'https://www.tertiarycourses.com.sg/google-software-training-in.html'),
('advanced java',1,'https://www.tertiarycourses.com.sg/java-programming-courses.html'),
('Advanced Java Training',1,'https://www.tertiarycourses.com.sg/java-programming-courses.html'),
('advanced javascript',1,'https://www.tertiarycourses.com.sg/javascript-training-courses-in.html'),
('advanced kubernetes',1,'https://www.tertiarycourses.com.sg/kubernetes-courses.html'),
('Advanced Kubernetes Training',1,'https://www.tertiarycourses.com.sg/kubernetes-courses.html'),
('advanced php',1,'https://www.tertiarycourses.com.sg/php-mysql-training-courses.html'),
('advanced php programing training',1,'https://www.tertiarycourses.com.sg/php-mysql-training-courses.html'),
('Advanced PHP Programming',1,'https://www.tertiarycourses.com.sg/php-mysql-training-courses.html'),
('advanced php training',1,'https://www.tertiarycourses.com.sg/php-mysql-training-courses.html'),
('advanced raspberry',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('advanced raspberry pi',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Advanced Raspberry Pi Essential Training',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Advanced Raspberry Pi Training',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Advanced Raspberry Pi Training (Sensehat included)',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('advanced react',1,'https://www.tertiarycourses.com.sg/react-js-courses.html'),
('Advanced React.js',1,'https://www.tertiarycourses.com.sg/react-js-courses.html'),
('ADVANCED REACT.JS TRAINING',1,'https://www.tertiarycourses.com.sg/react-js-courses.html'),
('advanced selenium',1,'https://www.tertiarycourses.com.sg/selenium-training.html'),
('Advanced Selenium Training',1,'https://www.tertiarycourses.com.sg/selenium-training.html'),
('Advanced Vue',1,'https://www.tertiarycourses.com.sg/pearson-vue-test-registration.html'),
('Advanced Vue.js',1,'https://www.tertiarycourses.com.sg/pearson-vue-test-registration.html'),
('Advanced Vue.js Training',1,'https://www.tertiarycourses.com.sg/pearson-vue-test-registration.html'),
('advnaced react',1,'https://www.tertiarycourses.com.sg/react-js-courses.html'),
('agentic',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('Agentic ai',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('agentic ai apps',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('agentic ai workflow',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('agentic framework',1,'https://www.tertiarycourses.com.sg/web-framework-courses.html'),
('agentic workflow',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('agents',1,'https://www.tertiarycourses.com.sg/voice-agents-and-video-agents-coures.html'),
('ai agents',1,'https://www.tertiarycourses.com.sg/voice-agents-and-video-agents-coures.html'),
('ai chat bot creation',1,'https://www.tertiarycourses.com.sg/genai-video-creation.html'),
('AI Chatbot',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('Ai ethics',1,'https://www.tertiarycourses.com.sg/ai-ethics-governance-courses.html'),
('ajax',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('andriod',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('Android',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('android app',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('android apps',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('android developer',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('android development course',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('Android mobile application',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('Animate CC - Rich Content Creation',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('Animation with Crazytalk animator',1,'https://www.tertiarycourses.com.sg/gaming-animation-and-video-courses-in.html'),
('Animation with CrazyTalk Animator o',1,'https://www.tertiarycourses.com.sg/gaming-animation-and-video-courses-in.html'),
('ANSIBLE FOR NETWORKING',1,'https://www.tertiarycourses.com.sg/networks-training-in.html'),
('apache',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('apache big data',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('Apache hadoop',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('Apache Hadoop Big Data',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('apache Hadoop Big Data Analysis',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('Apache Hadoop Big Data Training',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('apache hbase',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('Apache Hbase Training',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('apache solr',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('APACHE SOLR SEARCH PLATFORM TRAINING',1,'https://www.tertiarycourses.com.sg/google-cloud-platform-courses.html'),
('Apache Solr Training',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('Apple Swift Exam Inventory and Practice Test Exam Voucher',1,'https://www.tertiarycourses.com.sg/comptia-practice-exams.html'),
('Applications Integration with Robotic Process Automation',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('architecting on aws',1,'https://www.tertiarycourses.com.sg/aws-skill-builder.html'),
('architecting with aws',1,'https://www.tertiarycourses.com.sg/aws-skill-builder.html'),
('arduino',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Arduino advanced',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('arduino hobby kit',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('arduino kit',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('arduino robotics',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('arduino starter kit',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Arduino Training',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Arduino worshop for adults',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Aromatherapy course',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('Artificial Inteligent Robot',1,'https://www.tertiarycourses.com.sg/artificial-intelligence-for-kids-courses-and-workshops.html'),
('ARUBA NETWORK TRAINING',1,'https://www.tertiarycourses.com.sg/network-securities-courses.html'),
('Aurodesk exam voucher',1,'https://www.tertiarycourses.com.sg/autodesk-certificiation-exam-vouchers.html'),
('Autodesk Certified Professiona',1,'https://www.tertiarycourses.com.sg/autodesk-certificiation-exam-vouchers.html'),
('AutoDesk CFD Essential Training',1,'https://www.tertiarycourses.com.sg/autodesk-practice-exams.html'),
('Autodesk Exam voucher',1,'https://www.tertiarycourses.com.sg/autodesk-certificiation-exam-vouchers.html'),
('Autodesk exam vouchers',1,'https://www.tertiarycourses.com.sg/autodesk-certificiation-exam-vouchers.html'),
('autodesk voucher',1,'https://www.tertiarycourses.com.sg/autodesk-certificiation-exam-vouchers.html'),
('automation',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('automation excel',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('Automation testing',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('aws skill builder',1,'https://www.tertiarycourses.com.sg/aws-skill-builder.html'),
('aws skills builder',1,'https://www.tertiarycourses.com.sg/aws-skill-builder.html'),
('axure machine learning',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('azure AI',1,'https://www.tertiarycourses.com.sg/azure-cloud-computing-courses.html'),
('azure machine and deep learning',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('Azure Machine Learnin',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('azure machine learning',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('azure machine learning studio',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('Azure Machine Learning Studio Training',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('azure ml',1,'https://www.tertiarycourses.com.sg/azure-cloud-computing-courses.html'),
('azure mqchine learning',1,'https://www.tertiarycourses.com.sg/azure-cloud-computing-courses.html'),
('Basic BioPython Training for Bioinformatics',1,'https://www.tertiarycourses.com.sg/bioinformatics-courses.html'),
('basic blockchain bitcoin',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Basic Coding and Robotics using Micro:Bit',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('Basic Go Programming Training',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('basic java',1,'https://www.tertiarycourses.com.sg/java-programming-courses.html'),
('Basic Java Essential Training',1,'https://www.tertiarycourses.com.sg/java-programming-courses.html'),
('Basic java Programming',1,'https://www.tertiarycourses.com.sg/java-programming-courses.html'),
('basic machine learning with R',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('basic mean stack',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('Basic MEAN Stack Training',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('basic php',1,'https://www.tertiarycourses.com.sg/php-mysql-training-courses.html'),
('basic php training',1,'https://www.tertiarycourses.com.sg/php-mysql-training-courses.html'),
('Basic PHP Training for Beginners',1,'https://www.tertiarycourses.com.sg/php-mysql-training-courses.html'),
('basic programming with excel VBA',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('BASIC QLIKVIEW DATA ANALYTICS TRAINING',1,'https://www.tertiarycourses.com.sg/data-analytics-courses.html'),
('Basic Rhino',1,'https://www.tertiarycourses.com.sg/rhino-trainings.html'),
('Beauty therapy',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('Bells',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('big data',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('big data analytics',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('Bio',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('Bioinformatics',1,'https://www.tertiarycourses.com.sg/bioinformatics-courses.html'),
('Biomedical',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('bitcoin blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blender',1,'https://www.tertiarycourses.com.sg/blender-3d-software-training-in.html'),
('block chain programming',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain and bticoin course',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain and fintech',1,'https://www.tertiarycourses.com.sg/wsq-blockchain-fintech-courses.html'),
('Blockchain bitcoin',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain business',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain courses',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain development',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain for business',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain for hosptiality',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('BLOCKCHAIN FUNDAMENTALS',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain innovation',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Blockchain node',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain nodes',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('blockchain programming',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Blockchain Technology',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Body therapy',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('bootstrap',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('Build Agentic AI',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('building a chatbot',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('Building A Conversational Chatbot with Dialogflow',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('Building A Conversational Chatbot with Dialogflow (6 Pax)',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('BUILDING A TELEGRAM CHATBOT',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('Building Agentic AI Workflows to Automate Business',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('Building Agentic AI Workflows to Automate Business Processes',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('BUILDING MACHINE LEARNING WEB APPS WITH TENSORFLOW.JS',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('Building Powerful e-Commerce Stores with Magento',1,'https://www.tertiarycourses.com.sg/ecommerce-training-courses.html'),
('business architect',1,'https://www.tertiarycourses.com.sg/business-soft-skills-courses.html'),
('business blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('business innovation wsq nicf',1,'https://www.tertiarycourses.com.sg/business-soft-skills-courses.html'),
('business technology',1,'https://www.tertiarycourses.com.sg/computer-programming-and-infocomm-courses.html'),
('C and C#',1,'https://www.tertiarycourses.com.sg/c-cplusplus-csharp-training-in.html'),
('C# advance',1,'https://www.tertiarycourses.com.sg/c-cplusplus-csharp-training-in.html'),
('Certified digital marketer',1,'https://www.tertiarycourses.com.sg/digital-marketing-courses-in.html'),
('change management',1,'https://www.tertiarycourses.com.sg/wsq-project-management-courses.html'),
('Chatbot',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('chatbot telegram',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('ChatGPT',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('chatgpt api',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('chatgpt for content creation',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('chips design',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('CI/CD WITH JENKINS PIPELINE AND DOCKER',1,'https://www.tertiarycourses.com.sg/docker-courses.html'),
('cisco certification',1,'https://www.tertiarycourses.com.sg/cisco-certification-preparation-exam-courses.html'),
('Computational Thinking',1,'https://www.tertiarycourses.com.sg/design-thinking-courses.html'),
('content management systems',1,'https://www.tertiarycourses.com.sg/content-management-cms-skillsfuture-courses.html'),
('Content nanny course',1,'https://www.tertiarycourses.com.sg/content-management-cms-skillsfuture-courses.html'),
('contract law',1,'https://www.tertiarycourses.com.sg/smart-contract-courses.html'),
('cordova',1,'https://www.tertiarycourses.com.sg/mobile-programming-courses.html'),
('core ml',1,'https://www.tertiarycourses.com.sg/wsq-soft-skill-and-critical-core-skill-project-management-courses.html'),
('Corporate governance',1,'https://www.tertiarycourses.com.sg/corporate-governance-courses.html'),
('Create a Cross Platform Mobile Apps with Apache Cordova',1,'https://www.tertiarycourses.com.sg/cross-platform-hybrid-apps-courses.html'),
('Create a Cross Platform Mobile Apps with Apache Cordova Course Date',1,'https://www.tertiarycourses.com.sg/cross-platform-hybrid-apps-courses.html'),
('Create a Professional Website with Dreamweaver Training',1,'https://www.tertiarycourses.com.sg/website-feedback.html'),
('Create microservices with .NET and ASP.NET Core',1,'https://www.tertiarycourses.com.sg/wsq-soft-skill-and-critical-core-skill-project-management-courses.html'),
('crm',1,'https://www.tertiarycourses.com.sg/erp-crm-training-courses.html'),
('crypto',1,'https://www.tertiarycourses.com.sg/ibf-blockchain-fintech-courses.html'),
('cryptocurrencies',1,'https://www.tertiarycourses.com.sg/cryptocurrencies-courses.html'),
('cryptocurrency and blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Cryptography and Privacy in Blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('css animation',1,'https://www.tertiarycourses.com.sg/gaming-animation-and-video-courses-in.html'),
('css3 animation',1,'https://www.tertiarycourses.com.sg/gaming-animation-and-video-courses-in.html'),
('CSS3 Animation Training',1,'https://www.tertiarycourses.com.sg/gaming-animation-and-video-courses-in.html'),
('customer service',1,'https://www.tertiarycourses.com.sg/customer-service-training.html'),
('data structure',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('Day 1 of Apache Hadoop Big Data Training',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('Deep learning beginners',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Deep Learning for Beginner',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('deep learning for beginners',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Deep Learning for Beignners',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('deep learning in R',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Deep Learning NLP with spaCy',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('DEEP LEARNING NLP WITH SPACY.',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Deep Learning with Fast.Ai',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Deep Learning with Microsoft Cognitive Toolkit',1,'https://www.tertiarycourses.com.sg/microsoft-software-training.html'),
('DEEP LEARNING WITH R',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('deep learnning for beginners',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Deep machine learning for beginners',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Design and build responsive website from scratch',1,'https://www.tertiarycourses.com.sg/responsive-web-design-training-in.html'),
('design of experiment',1,'https://www.tertiarycourses.com.sg/design-of-experiment-courses.html'),
('design of experiments',1,'https://www.tertiarycourses.com.sg/design-of-experiment-courses.html'),
('development',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('Dialogbox chatbot',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('Dialogflow AI Chatbot Platform Management for Begi',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('Dialogflow AI Chatbot Platform Management for Beginners',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('digital',1,'https://www.tertiarycourses.com.sg/digital-marketing-courses-in.html'),
('docker administration',1,'https://www.tertiarycourses.com.sg/docker-courses.html'),
('docker container',1,'https://www.tertiarycourses.com.sg/docker-courses.html'),
('Docker Deep Dive',1,'https://www.tertiarycourses.com.sg/docker-courses.html'),
('DOCKER ESSENTIAL',1,'https://www.tertiarycourses.com.sg/docker-courses.html'),
('Docker Essential Training',1,'https://www.tertiarycourses.com.sg/docker-courses.html'),
('docker essentials',1,'https://www.tertiarycourses.com.sg/docker-courses.html'),
('Drones',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('drupal',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('effective communication',1,'https://www.tertiarycourses.com.sg/communication-courses.html'),
('effective communication within the workplace',1,'https://www.tertiarycourses.com.sg/communication-courses.html'),
('effective workplace',1,'https://www.tertiarycourses.com.sg/workplace-learning-consultancy.html'),
('Effective Workplace Communications',1,'https://www.tertiarycourses.com.sg/workplace-learning-consultancy.html'),
('Electronic',1,'https://www.tertiarycourses.com.sg/robotics-workshops-kids.html'),
('Embedded C Programming Course',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('embedded programming',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('Embedded system',1,'https://www.tertiarycourses.com.sg/linux-operating-system-training.html'),
('Embedded systems',1,'https://www.tertiarycourses.com.sg/operating-systems-training-courses.html'),
('enerative Adversarial Networks (GAN) Course for Beginners',1,'https://www.tertiarycourses.com.sg/networks-training-in.html'),
('erp',1,'https://www.tertiarycourses.com.sg/erp-crm-training-courses.html'),
('ERP AND CRM TRAINING WITH ODOO',1,'https://www.tertiarycourses.com.sg/erp-crm-training-courses.html'),
('ESP8266 IoT',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('Essential Machine Learning with R',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('ethereum',1,'https://www.tertiarycourses.com.sg/ethereum-skillsfuture-courses-in.html'),
('Ethereum Blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('etherum smart contract',1,'https://www.tertiarycourses.com.sg/smart-contract-courses.html'),
('exam vouchers',1,'https://www.tertiarycourses.com.sg/autodesk-certificiation-exam-vouchers.html'),
('excel prep',1,'https://www.tertiarycourses.com.sg/microsoft-excel-trainings.html'),
('Finance accounting',1,'https://www.tertiarycourses.com.sg/wsq-finance-accounting-courses.html'),
('financial services',1,'https://www.tertiarycourses.com.sg/fintech-courses.html'),
('Fintech',1,'https://www.tertiarycourses.com.sg/fintech-courses.html'),
('Floral design',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('flower design',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('food hygiene',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('fts',1,'https://www.tertiarycourses.com.sg/ibf-sts-investment-and-financial-analysis-courses.html'),
('fts blockchain',1,'https://www.tertiarycourses.com.sg/ibf-blockchain-fintech-courses.html'),
('full mean stack',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('Full MEAN Stack Training',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('full ros navigation',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('Full ROS Navigation Course',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('Fuul ROS navigation course',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('game design for kids',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('generative',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('Generative Adversarial Network',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('Generative Adversarial Networks',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('Generative Adversarial Networks (GAN) Course for Beginners',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('Generative Adversial Network',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('generative modeling',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('Git Essential Training',1,'https://www.tertiarycourses.com.sg/git-and-github-courses.html'),
('git hub',1,'https://www.tertiarycourses.com.sg/git-and-github-courses.html'),
('goggle',1,'https://www.tertiarycourses.com.sg/google-software-training-in.html'),
('Goo',1,'https://www.tertiarycourses.com.sg/google-software-training-in.html'),
('Google',1,'https://www.tertiarycourses.com.sg/google-software-training-in.html'),
('google ad',1,'https://www.tertiarycourses.com.sg/digital-advertising-ppc-courses.html'),
('google ads certificate',1,'https://www.tertiarycourses.com.sg/google-adwords-courses.html'),
('google ads certification',1,'https://www.tertiarycourses.com.sg/google-adwords-courses.html'),
('google dialogflow',1,'https://www.tertiarycourses.com.sg/google-cloud-practice-exams.html'),
('google firebase',1,'https://www.tertiarycourses.com.sg/google-cloud-practice-exams.html'),
('Google Firebase for android learning',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('Google Firebase For Android Training',1,'https://www.tertiarycourses.com.sg/android-programming-courses-in.html'),
('google msarketimg',1,'https://www.tertiarycourses.com.sg/digital-advertising-ppc-courses.html'),
('growth hacking',1,'https://www.tertiarycourses.com.sg/pentest-ethical-hacking-courses.html'),
('Hadoop big',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('hadoop big data',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('Hadoop Big Data Analysis',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('HDL Programming Training for FPGA',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('home internet',1,'https://www.tertiarycourses.com.sg/internet-of-things-iot-training-in.html'),
('hospitality blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Huawei Certified Network Associate (HCNA) Certification Prep',1,'https://www.tertiarycourses.com.sg/network-securities-courses.html'),
('Human Resources Management',1,'https://www.tertiarycourses.com.sg/human-resource-management-courses.html'),
('Hygiene',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('Hypnotherapy',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('IBM cloud',1,'https://www.tertiarycourses.com.sg/google-cloud-practice-exams.html'),
('IBM Quantum Practitioners Course',1,'https://www.tertiarycourses.com.sg/wsq-quantum-computing-courses.html'),
('ibm skills',1,'https://www.tertiarycourses.com.sg/business-soft-skills-courses.html'),
('illustrator',1,'https://www.tertiarycourses.com.sg/adobe-illustrator-courses.html'),
('infographics',1,'https://www.tertiarycourses.com.sg/infographics-courses.html'),
('Instructional design',1,'https://www.tertiarycourses.com.sg/instructional-design-courses.html'),
('Interactive Web Apps Presentation Using Shiny & R',1,'https://www.tertiarycourses.com.sg/mobile-programming-courses.html'),
('Intermediate scratch coding',1,'https://www.tertiarycourses.com.sg/ibf-programming-and-coding-courses.html'),
('Internal Auditor Course',1,'https://www.tertiarycourses.com.sg/iso-internal-auditor-courses.html'),
('investment',1,'https://www.tertiarycourses.com.sg/investment-courses-in.html'),
('IoT ESP8266',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('Iot microbit',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('IoT Training with ESP8266 Wi-Fi Controller',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('IoT Training with Raspberry Pi Zero W',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('ISO 9001 lead auditor',1,'https://www.tertiarycourses.com.sg/iso-internal-auditor-courses.html'),
('ISO 9001 Lead Auditor Training',1,'https://www.tertiarycourses.com.sg/iso-internal-auditor-courses.html'),
('IT Networking',1,'https://www.tertiarycourses.com.sg/networks-training-in.html'),
('ITIL 4',1,'https://www.tertiarycourses.com.sg/itil-4-certification-exam-prep-courses.html'),
('java advance',1,'https://www.tertiarycourses.com.sg/java-programming-courses.html'),
('javascript',1,'https://www.tertiarycourses.com.sg/javascript-training-courses-in.html'),
('JSON Python',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('JSON Training with C# and Javascript',1,'https://www.tertiarycourses.com.sg/javascript-training-courses-in.html'),
('keras vision',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('Learn Basic Coding and Robotics using Micro:Bit',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('LEARNING ROS ON RASPBERRY PI',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Learning ROS2 on Raspberry Pi',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('level 1 foundation training',1,'https://www.tertiarycourses.com.sg/linux-foundation-certification-exam-prep-courses.html'),
('leverage big data',1,'https://www.tertiarycourses.com.sg/data-engineering-big-data-courses.html'),
('Life science',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('lightroom',1,'https://www.tertiarycourses.com.sg/adobe-lightroom-courses.html'),
('LLM chatbot',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('mac os support',1,'https://www.tertiarycourses.com.sg/support.html'),
('mac os support essentials',1,'https://www.tertiarycourses.com.sg/support.html'),
('mac os support essentials apple',1,'https://www.tertiarycourses.com.sg/support.html'),
('machine learning in R',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('Machine Learning on iOS Devices with Core ML',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('Machine Learning with H2O.ai',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('machine r',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('Macro vba',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('maen stack',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('Magento',1,'https://www.tertiarycourses.com.sg/magento-training-courses-in.html'),
('magento administration',1,'https://www.tertiarycourses.com.sg/magento-training-courses-in.html'),
('magento ecommerce',1,'https://www.tertiarycourses.com.sg/magento-training-courses-in.html'),
('Magento eCommerce Administrator Training',1,'https://www.tertiarycourses.com.sg/ecommerce-training-courses.html'),
('Manufacturing',1,'https://www.tertiarycourses.com.sg/logistics-and-manufacturing-courses.html'),
('MARIADB DATABASE TRAINING',1,'https://www.tertiarycourses.com.sg/database.html'),
('massage',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('master ai agentic',1,'https://www.tertiarycourses.com.sg/ai-agent-courses.html'),
('Master eCommerce SEO Strategies to Increase Traffic and Sales',1,'https://www.tertiarycourses.com.sg/ecommerce-training-courses.html'),
('Mastering the Art of Communication to Enhance Team Collaboration and Customer Satisfaction',1,'https://www.tertiarycourses.com.sg/new-course-collaboration.html'),
('maya',1,'https://www.tertiarycourses.com.sg/autodesk-maya-trainings.html'),
('mbedded C Programming Course',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('mean stack',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('MEAN Stack Development Essential Training',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('Meta Certified Creative Strategy Professional',1,'https://www.tertiarycourses.com.sg/creative-art-for-kids-workshops.html'),
('Meta Certified Digital Marketing Associate Exam Prep',1,'https://www.tertiarycourses.com.sg/digital-marketing-courses-in.html'),
('meta spark',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('microbit iot',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('microcontroller',1,'https://www.tertiarycourses.com.sg/pic-microcontroller-courses.html'),
('Microcontroller Training',1,'https://www.tertiarycourses.com.sg/pic-microcontroller-courses.html'),
('Microsoft Azure Machine Learning Studio Training',1,'https://www.tertiarycourses.com.sg/microsoft-copilot-studio-agents.html'),
('microsoft fundamental exam',1,'https://www.tertiarycourses.com.sg/microsoft-software-training.html'),
('Microsoft PowerPoint',1,'https://www.tertiarycourses.com.sg/microsoft-powerpoint-training.html'),
('microsoft visual basic',1,'https://www.tertiarycourses.com.sg/digital-drawing-for-kids.html'),
('MOODLECLOUD LMS ESSENTIAL TRAINING',1,'https://www.tertiarycourses.com.sg/learning-management-system-lms-courses.html'),
('MOS excel',1,'https://www.tertiarycourses.com.sg/microsoft-excel-trainings.html'),
('MOS Excel Exam 77-728 Prep',1,'https://www.tertiarycourses.com.sg/microsoft-excel-trainings.html'),
('motion graphic',1,'https://www.tertiarycourses.com.sg/gaming-animation-and-video-courses-in.html'),
('MS-900 Microsoft 365 Fundamentals Exam Prep',1,'https://www.tertiarycourses.com.sg/microsoft-365-software-training.html'),
('MS900',1,'https://www.tertiarycourses.com.sg/microsoft-365-software-training.html'),
('narrative therapy',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('Natural language',1,'https://www.tertiarycourses.com.sg/art-and-language-workshops-for-kids.html'),
('Natural Language Processing',1,'https://www.tertiarycourses.com.sg/art-and-language-workshops-for-kids.html'),
('Natural Language Processing (NLP) with Python for Beginner',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('natural language processing with r',1,'https://www.tertiarycourses.com.sg/art-and-language-workshops-for-kids.html'),
('network',1,'https://www.tertiarycourses.com.sg/network-securities-courses.html'),
('Networking',1,'https://www.tertiarycourses.com.sg/networks-training-in.html'),
('networking fundamentals',1,'https://www.tertiarycourses.com.sg/networks-training-in.html'),
('nft',1,'https://www.tertiarycourses.com.sg/non-fungible-tokens-nft-courses.html'),
('NICF - Magento e-Commerce Content Management',1,'https://www.tertiarycourses.com.sg/content-management-cms-skillsfuture-courses.html'),
('NICF - NFT Opportunities for Digital Artists and Businesses',1,'https://www.tertiarycourses.com.sg/digital-marketing-courses-in.html'),
('NICF - NFT Opportunities for Digital Artists and Businesses.',1,'https://www.tertiarycourses.com.sg/digital-marketing-courses-in.html'),
('NICF - Robotics Process Automation (RPA) for Beginners',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('NICF - Search Engine Optimization (SEO) for e-Commerce',1,'https://www.tertiarycourses.com.sg/search-engine-optimisation-seo-training-courses.html'),
('NICF - System integration with Robot Operating System (ROS)',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('NICF – Natural Language Processing (NLP) with Python for Beginners',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('NICF – Software Automation with Excel VBA Programming',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('NICF – Software Design with Vue.js Framework',1,'https://www.tertiarycourses.com.sg/microsoft-software-training.html'),
('Non fungible token',1,'https://www.tertiarycourses.com.sg/non-fungible-tokens-nft-courses.html'),
('nurse',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('NURSING',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('o level python',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('office for kids',1,'https://www.tertiarycourses.com.sg/kid-workshops-tours.html'),
('Opcua',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('opensea',1,'https://www.tertiarycourses.com.sg/non-fungible-tokens-nft-courses.html'),
('outsystems',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('Passive Income Through Real Estate Investment Trust',1,'https://www.tertiarycourses.com.sg/investment-courses-in.html'),
('Personal development',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('photoshop',1,'https://www.tertiarycourses.com.sg/adobe-photoshop-courses.html'),
('photoshop cc',1,'https://www.tertiarycourses.com.sg/adobe-photoshop-courses.html'),
('PIC',1,'https://www.tertiarycourses.com.sg/pic-microcontroller-courses.html'),
('pic controller',1,'https://www.tertiarycourses.com.sg/pic-microcontroller-courses.html'),
('PIC microcontroller',1,'https://www.tertiarycourses.com.sg/pic-microcontroller-courses.html'),
('pic32',1,'https://www.tertiarycourses.com.sg/pic-microcontroller-courses.html'),
('plant science',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('Plc',1,'https://www.tertiarycourses.com.sg/pic-microcontroller-courses.html'),
('power BI',1,'https://www.tertiarycourses.com.sg/power-automate-software-training.html'),
('power virtual',1,'https://www.tertiarycourses.com.sg/power-automate-software-training.html'),
('powerpoint',1,'https://www.tertiarycourses.com.sg/microsoft-powerpoint-training.html'),
('PPC',1,'https://www.tertiarycourses.com.sg/digital-advertising-ppc-courses.html'),
('practice exams',1,'https://www.tertiarycourses.com.sg/comptia-practice-exams.html'),
('Practice Test',1,'https://www.tertiarycourses.com.sg/autodesk-practice-exams.html'),
('premeire',1,'https://www.tertiarycourses.com.sg/adobe-premiere-pro-courses.html'),
('premeire pro',1,'https://www.tertiarycourses.com.sg/adobe-premiere-pro-courses.html'),
('programming with VBA',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('python automation',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('python kids',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('python network automation',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('Python Network Automation Training',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('python NLP',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('python scikit',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('Python Scikit Learn',1,'https://www.tertiarycourses.com.sg/python-programming.html'),
('QGis',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('Qlik',1,'https://www.tertiarycourses.com.sg/qlikviiew-qliksense-software-training-courses.html'),
('qlik view',1,'https://www.tertiarycourses.com.sg/qlikviiew-qliksense-software-training-courses.html'),
('qoo10-sales-manager-gsm-training.',1,'https://www.tertiarycourses.com.sg/google-tag-manager-courses.html'),
('qoo10-sales-manager-gsm-training.html',1,'https://www.tertiarycourses.com.sg/google-tag-manager-courses.html'),
('Quality ISO',1,'https://www.tertiarycourses.com.sg/iso-standards-courses.html'),
('quickbooks pro',1,'https://www.tertiarycourses.com.sg/quickbooks-training-courses.html'),
('QuickBooks Pro Training (Desktop Version)',1,'https://www.tertiarycourses.com.sg/quickbooks-training-courses.html'),
('R analysis',1,'https://www.tertiarycourses.com.sg/failure-analysis-courses.html'),
('R analytics',1,'https://www.tertiarycourses.com.sg/data-analytics-courses.html'),
('r deep learning',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('R deep learning with keras',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('r machine',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('r machine learning',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('R programming',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('rarible',1,'https://www.tertiarycourses.com.sg/non-fungible-tokens-nft-courses.html'),
('raspberry',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('raspberry pi',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Raspberry pi advanced',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Raspberry Pi for Teenagers',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Raspberry Pi IoT with Power BI',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Raspberry Pi Kit',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Raspberry Pi Training',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('raspberry pi zero',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Raspberry Pi Zero IoT',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('raspberry pi zero w',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Realistic Architectural Visualization with 3DS MAX and Mental Ray',1,'https://www.tertiarycourses.com.sg/autodesk-3ds-max-trainings.html'),
('responsive',1,'https://www.tertiarycourses.com.sg/responsive-web-design-training-in.html'),
('responsive web',1,'https://www.tertiarycourses.com.sg/responsive-web-design-training-in.html'),
('responsive web design',1,'https://www.tertiarycourses.com.sg/responsive-web-design-training-in.html'),
('Responsive Web Design Training',1,'https://www.tertiarycourses.com.sg/responsive-web-design-training-in.html'),
('responsive website',1,'https://www.tertiarycourses.com.sg/responsive-web-design-training-in.html'),
('robot',1,'https://www.tertiarycourses.com.sg/robotics-workshops-kids.html'),
('robot arm',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('robot arm ai',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('robot arm control',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('robot print',1,'https://www.tertiarycourses.com.sg/robotics-workshops-kids.html'),
('Robotic',1,'https://www.tertiarycourses.com.sg/robotics-workshops-kids.html'),
('Robotic Process Automation RPA with UIPath Mode of Training',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('Robotics',1,'https://www.tertiarycourses.com.sg/robotics-workshops-kids.html'),
('Robotics Process Automation  for Beginners',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('Robots',1,'https://www.tertiarycourses.com.sg/robotics-workshops-kids.html'),
('ros 2 navigation',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ros ai pick and place',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ros ai pickup',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ros arm',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ROS fundamental',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ROS navigation',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ROS NAVIGATION COURSE',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ROS python',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('ROS Raspberry Pi',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('ros robot arm',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('RPA for beginners',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('ruby programming',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('Ruby Programming Training',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('SAP ERP',1,'https://www.tertiarycourses.com.sg/erp-crm-training-courses.html'),
('scikit machine',1,'https://www.tertiarycourses.com.sg/machine-learning-courses.html'),
('Scratch Programming',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('Scratch Programming Training',1,'https://www.tertiarycourses.com.sg/programming-courses.html'),
('Search Engine Optimisation (SEO) for eCommerce Store',1,'https://www.tertiarycourses.com.sg/search-engine-optimisation-seo-training-courses.html'),
('secure coding',1,'https://www.tertiarycourses.com.sg/genai-coding-for-kids.html'),
('Secure Coding in Java Course',1,'https://www.tertiarycourses.com.sg/genai-coding-for-kids.html'),
('security application development',1,'https://www.tertiarycourses.com.sg/full-stack-web-application-courses.html'),
('seo ecommerce',1,'https://www.tertiarycourses.com.sg/ecommerce-training-courses.html'),
('SEO for SME',1,'https://www.tertiarycourses.com.sg/search-engine-optimisation-seo-training-courses.html'),
('seo in ecommerce',1,'https://www.tertiarycourses.com.sg/ecommerce-training-courses.html'),
('Sero',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('Skill Builder',1,'https://www.tertiarycourses.com.sg/aws-skill-builder.html'),
('skills builder',1,'https://www.tertiarycourses.com.sg/aws-skill-builder.html'),
('skills future',1,'https://www.tertiarycourses.com.sg/business-soft-skills-courses.html'),
('skillsfuture claim',1,'https://www.tertiarycourses.com.sg/claim-skillsfuture-claim.html'),
('skillsfuture credit claim',1,'https://www.tertiarycourses.com.sg/claim-skillsfuture-claim.html'),
('Skillsfuture for digital workplace',1,'https://www.tertiarycourses.com.sg/workplace-learning-consultancy.html'),
('sklll builder',1,'https://www.tertiarycourses.com.sg/aws-skill-builder.html'),
('smart home',1,'https://www.tertiarycourses.com.sg/robotics-workshops-kids.html'),
('Software Automation with Excel VBA Programming',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('Software automation with excel via',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('software automation with vba',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('software developer',1,'https://www.tertiarycourses.com.sg/microsoft-software-training.html'),
('spark ar',1,'https://www.tertiarycourses.com.sg/apache-spark-courses.html'),
('spc in manufacturing',1,'https://www.tertiarycourses.com.sg/electronics-semiconductor-spc-courses.html'),
('Speech therapy',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('Speech therapy for special needs',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('statistical analysis',1,'https://www.tertiarycourses.com.sg/failure-analysis-courses.html'),
('Statistical Process Control (SPC) in Manufacturing',1,'https://www.tertiarycourses.com.sg/electronics-semiconductor-spc-courses.html'),
('statistical Process Control in manufacturing',1,'https://www.tertiarycourses.com.sg/logistics-and-manufacturing-courses.html'),
('submit skills future payment claims',1,'https://www.tertiarycourses.com.sg/business-soft-skills-courses.html'),
('suite',1,'https://www.tertiarycourses.com.sg/google-g-suite-trainings.html'),
('System integration with Robot Operating System (ROS)',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('tableau',1,'https://www.tertiarycourses.com.sg/tableau-software-courses.html'),
('tableau certification',1,'https://www.tertiarycourses.com.sg/tableau-software-courses.html'),
('text analysis',1,'https://www.tertiarycourses.com.sg/failure-analysis-courses.html'),
('text analytics',1,'https://www.tertiarycourses.com.sg/data-analytics-courses.html'),
('therapy',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('therapy assistant',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('therapy services',1,'https://www.tertiarycourses.com.sg/fintech-courses.html'),
('time management',1,'https://www.tertiarycourses.com.sg/wsq-project-management-courses.html'),
('Time Series Analysis in R',1,'https://www.tertiarycourses.com.sg/failure-analysis-courses.html'),
('Time series Forecasting in R',1,'https://www.tertiarycourses.com.sg/jobs.html'),
('time series in r',1,'https://www.tertiarycourses.com.sg/jobs.html'),
('tosca',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('Trainer',1,'https://www.tertiarycourses.com.sg/trainer-application.html'),
('trainer staff',1,'https://www.tertiarycourses.com.sg/trainer-application.html'),
('utap',1,'https://www.tertiarycourses.com.sg/wsq-ibf-skillsfuture-utap-funded-courses.html'),
('vector database',1,'https://www.tertiarycourses.com.sg/database.html'),
('vision keras',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('VISUAL BASIC VB.NET ESSENTIAL TRAINING',1,'https://www.tertiarycourses.com.sg/digital-drawing-for-kids.html'),
('visual basic.net',1,'https://www.tertiarycourses.com.sg/digital-drawing-for-kids.html'),
('Visual basics',1,'https://www.tertiarycourses.com.sg/digital-drawing-for-kids.html'),
('visual coding',1,'https://www.tertiarycourses.com.sg/genai-coding-for-kids.html'),
('Visual Coding with Arduino for Non-Programmers',1,'https://www.tertiarycourses.com.sg/arduino-courses-in.html'),
('Visualising Raspberry Pi IoT with Power BI',1,'https://www.tertiarycourses.com.sg/raspberry-pi-courses-in.html'),
('Visualising Raspbery Pi IoT with Power BI',1,'https://www.tertiarycourses.com.sg/power-automate-software-training.html'),
('Visualising Raspbery Pi loT with power BI',1,'https://www.tertiarycourses.com.sg/power-automate-software-training.html'),
('vouchers',1,'https://www.tertiarycourses.com.sg/autodesk-certificiation-exam-vouchers.html'),
('Vue JS Essential Training',1,'https://www.tertiarycourses.com.sg/pearson-vue-test-registration.html'),
('Vue.js Essential Training',1,'https://www.tertiarycourses.com.sg/pearson-vue-test-registration.html'),
('waq blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('Web',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('Web 3 and Metaverse Awareness Course',1,'https://www.tertiarycourses.com.sg/metaverse-courses.html'),
('web developer',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('web page design',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('Web scraping',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('wiley deep learning',1,'https://www.tertiarycourses.com.sg/deep-learning-computer-vision-courses.html'),
('windows',1,'https://www.tertiarycourses.com.sg/microsoft-windows-10-training.html'),
('windows 10',1,'https://www.tertiarycourses.com.sg/microsoft-windows-10-training.html'),
('WINDOWS 10 ESSENTIAL TRAINING',1,'https://www.tertiarycourses.com.sg/microsoft-windows-10-training.html'),
('windows security',1,'https://www.tertiarycourses.com.sg/microsoft-windows-10-training.html'),
('wordpres',1,'https://www.tertiarycourses.com.sg/wordpress-web-deisgn.html'),
('WordPress',1,'https://www.tertiarycourses.com.sg/wordpress-web-deisgn.html'),
('workplace communication',1,'https://www.tertiarycourses.com.sg/workplace-learning-consultancy.html'),
('Workpress',1,'https://www.tertiarycourses.com.sg/wordpress-web-deisgn.html'),
('world blockchain',1,'https://www.tertiarycourses.com.sg/blockchain-courses.html'),
('wsa vba',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('WSQ - Cyber',1,'https://www.tertiarycourses.com.sg/cyber-security-digital-forensic-training-courses.html'),
('WSQ - Dialog????ow AI Chatbot Platform Management for Beginners',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('WSQ - Dialogflow AI Chatbot Platform Management fo',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('WSQ - Dialogflow AI Chatbot Platform Management for',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('WSQ - Dialogflow AI Chatbot Platform Management for Beginners',1,'https://www.tertiarycourses.com.sg/chatbot-html.html'),
('WSQ - Effective Workplace Communications',1,'https://www.tertiarycourses.com.sg/workplace-learning-consultancy.html'),
('WSQ - Internet of Things (IoT) Fundamental of Beginners',1,'https://www.tertiarycourses.com.sg/internet-of-things-iot-training-in.html'),
('WSQ - NICF - Computational Modeling with Generative Adversarial Network (GAN)',1,'https://www.tertiarycourses.com.sg/chatgpt-and-generative-ai-courses.html'),
('WSQ - Search Engine Optimization (SEO) for e-Commerce',1,'https://www.tertiarycourses.com.sg/search-engine-optimisation-seo-training-courses.html'),
('WSQ - Search Engine Optimization for Small and Medium',1,'https://www.tertiarycourses.com.sg/search-engine-optimisation-seo-training-courses.html'),
('WSQ - Search Engine Optimization for Small and Medium Enterprises',1,'https://www.tertiarycourses.com.sg/search-engine-optimisation-seo-training-courses.html'),
('WSQ - Statistical Prgocess Control (SPC) in Manufacturing',1,'https://www.tertiarycourses.com.sg/electronics-semiconductor-spc-courses.html'),
('WSQ - Statistical Process Control (SPC) in Manufacturing',1,'https://www.tertiarycourses.com.sg/electronics-semiconductor-spc-courses.html'),
('WSQ Advanced Certificate in Training and Assessment',1,'https://www.tertiarycourses.com.sg/assessment-appeal-form.html'),
('WSQ Advanced Certificate in Training and Assessment (ACTA)',1,'https://www.tertiarycourses.com.sg/assessment-appeal-form.html'),
('Wsq apply food safety management system',1,'https://www.tertiarycourses.com.sg/learning-management-system-lms-courses.html'),
('wsq bootstrap',1,'https://www.tertiarycourses.com.sg/web-design-courses.html'),
('WSQ Effective Workplace communication',1,'https://www.tertiarycourses.com.sg/workplace-learning-consultancy.html'),
('wsq iot',1,'https://www.tertiarycourses.com.sg/iot-robotics-courses-in.html'),
('wsq magento',1,'https://www.tertiarycourses.com.sg/magento-training-courses-in.html'),
('wsq nft',1,'https://www.tertiarycourses.com.sg/non-fungible-tokens-nft-courses.html'),
('wsq ros',1,'https://www.tertiarycourses.com.sg/robot-operating-system-ros-courses.html'),
('wsq rpa',1,'https://www.tertiarycourses.com.sg/rpa-api-it-automation-courses.html'),
('wsq search engine',1,'https://www.tertiarycourses.com.sg/search-engine-optimisation-seo-training-courses.html'),
('wsq seo ecommerce',1,'https://www.tertiarycourses.com.sg/ecommerce-training-courses.html'),
('wsq spc',1,'https://www.tertiarycourses.com.sg/electronics-semiconductor-spc-courses.html'),
('wsq text analytics',1,'https://www.tertiarycourses.com.sg/data-analytics-courses.html'),
('wsq vba',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('wsq vue',1,'https://www.tertiarycourses.com.sg/pearson-vue-test-registration.html'),
('wsq vue.js',1,'https://www.tertiarycourses.com.sg/pearson-vue-test-registration.html'),
('WSQ – Software Automation with Excel VBA Programming',1,'https://www.tertiarycourses.com.sg/vba-training-courses.html'),
('xamarin form',1,'https://www.tertiarycourses.com.sg/assessment-appeal-form.html'),
('xero',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('Xero account',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('xero accounting',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('Xero Accounting Soft',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('Xero Advisor Certification Training',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('xero training course',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('xeroo',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('xeros',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('Xerox',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('yoga',1,'https://www.tertiarycourses.com.sg/life-science-courses-training.html'),
('zero',1,'https://www.tertiarycourses.com.sg/xero-software-training.html'),
('zero accounting',1,'https://www.tertiarycourses.com.sg/accounting-software-training.html'),
('[ZOOM] ERP and CRM Training with Odoo',1,'https://www.tertiarycourses.com.sg/erp-crm-training-courses.html'),
('3d unity',2,'https://www.tertiarycourses.com.my/unity-training-courses.html'),
(':R Machine Learning Training',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('Advanced PHP Programming',2,'https://www.tertiarycourses.com.my/programming-courses.html'),
('agentic ai',2,'https://www.tertiarycourses.com.my/ai-agent-courses.html'),
('Agentic AI training',2,'https://www.tertiarycourses.com.my/ai-agent-courses.html'),
('Analytics and machine learning',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('Apache Hadoop',2,'https://www.tertiarycourses.com.my/apache-spark-courses.html'),
('Apache Hadoop Big Data',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('Apache Hadoop Big Data Training',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('apache solr',2,'https://www.tertiarycourses.com.my/apache-spark-courses.html'),
('Aquaponics',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('Aquaponics course',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('autodesk cfd',2,'https://www.tertiarycourses.com.my/autodesk-practice-exams.html'),
('Autodesk MudBox Essential Training',2,'https://www.tertiarycourses.com.my/autodesk-practice-exams.html'),
('axure machine learning',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('azure machine learning',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('azure machine learning studio',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('Azure Machine Learning Studio Training',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('big data',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('big data analytics',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('Big Data Hadoop Data Analysis Training',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('big data training',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('Building A Conversational Chatbot',2,'https://www.tertiarycourses.com.my/chatbot-html.html'),
('Building Machine Learning Web Apps with Tensorflow.js',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('chatbot',2,'https://www.tertiarycourses.com.my/chatbot-html.html'),
('coding for unity',2,'https://www.tertiarycourses.com.my/unity-training-courses.html'),
('communication',2,'https://www.tertiarycourses.com.my/communication-courses.html'),
('communication skill',2,'https://www.tertiarycourses.com.my/communication-courses.html'),
('Conversational Chatbot with Dialogflow',2,'https://www.tertiarycourses.com.my/chatbot-html.html'),
('core machine learning',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('Create a Professional Website with Dreamweaver Training',2,'https://www.tertiarycourses.com.my/website-feedback.html'),
('Deep Learning for Beginners',2,'https://www.tertiarycourses.com.my/deep-learning-computer-vision-courses.html'),
('Deep Learning NLP with spaCy',2,'https://www.tertiarycourses.com.my/deep-learning-computer-vision-courses.html'),
('Deep Learning with Keras',2,'https://www.tertiarycourses.com.my/deep-learning-computer-vision-courses.html'),
('Deep Learning with Microsoft Cognitive Toolkit',2,'https://www.tertiarycourses.com.my/microsoft-software-training.html'),
('Deep Learning with R',2,'https://www.tertiarycourses.com.my/deep-learning-computer-vision-courses.html'),
('deep learning withh r',2,'https://www.tertiarycourses.com.my/deep-learning-computer-vision-courses.html'),
('ESP32-CAM',2,'https://www.tertiarycourses.com.my/video-marketing-live-streaming.html'),
('ESSENTIAL MACHINE LEARNING WITH r',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('hadoop big data',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('hadoop big data training',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('hadoop data analysis',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('Hadoop Data Analysis Training',2,'https://www.tertiarycourses.com.my/data-engineering-big-data-courses.html'),
('hidroponic',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('hidroponik',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('Hydrophonic',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('hydrophonics',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('hydroponic',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('hydroponic farming course in sarawak',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('hydroponics',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('live streaming',2,'https://www.tertiarycourses.com.my/video-marketing-live-streaming.html'),
('llm',2,'https://www.tertiarycourses.com.my/generative-ai-gai-llm-courses.html'),
('machine',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('machine learning',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('machine learning in r',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('Machine Learning on iOS Devices with Core ML',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('r machine',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('r machine learning',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('R Machine Learning Training',2,'https://www.tertiarycourses.com.my/machine-learning-courses.html'),
('safety',2,'https://www.tertiarycourses.com.my/wsh-workplace-safety-health-courses.html'),
('six sigma',2,'https://www.tertiarycourses.com.my/six-sigma-certification-coures.html'),
('statistical analysis',2,'https://www.tertiarycourses.com.my/failure-analysis-courses.html'),
('time series',2,'https://www.tertiarycourses.com.my/jobs.html'),
('time series analysis',2,'https://www.tertiarycourses.com.my/failure-analysis-courses.html'),
('time series forecasting',2,'https://www.tertiarycourses.com.my/jobs.html'),
('Time Series forecasting in R',2,'https://www.tertiarycourses.com.my/jobs.html'),
('time series in R',2,'https://www.tertiarycourses.com.my/jobs.html'),
('time series R',2,'https://www.tertiarycourses.com.my/jobs.html'),
('unity',2,'https://www.tertiarycourses.com.my/unity-training-courses.html'),
('Urban Farming with Hydroponics Course',2,'https://www.tertiarycourses.com.my/hydroponics-urban-farming-courses.html'),
('vouchers',2,'https://www.tertiarycourses.com.my/autodesk-certificiation-exam-vouchers.html'),
('website',2,'https://www.tertiarycourses.com.my/website-feedback.html'),
('Wiley Certified Deep Learning Specialist',2,'https://www.tertiarycourses.com.my/pearson-vue-it-specialist-exam-vouchers.html'),
('workplace safety',2,'https://www.tertiarycourses.com.my/wsh-workplace-safety-health-courses.html'),
('3d printing',3,'https://www.tertiarycourses.com.gh/3d-printing-training-courses.html'),
('accounting',3,'https://www.tertiarycourses.com.gh/accounting-software-training.html'),
('advanced raspberry pi',3,'https://www.tertiarycourses.com.gh/raspberry-pi-courses-in.html'),
('after effects',3,'https://www.tertiarycourses.com.gh/adobe-after-effects-courses.html'),
('algorithmic trading',3,'https://www.tertiarycourses.com.gh/algorithmic-trading-quantitative-analysis-courses.html'),
('Android',3,'https://www.tertiarycourses.com.gh/android-programming-courses-in.html'),
('Animation',3,'https://www.tertiarycourses.com.gh/gaming-animation-and-video-courses-in.html'),
('api',3,'https://www.tertiarycourses.com.gh/rpa-api-it-automation-courses.html'),
('arduino',3,'https://www.tertiarycourses.com.gh/arduino-courses-in.html'),
('Auto card',3,'https://www.tertiarycourses.com.gh/autodesk-autocad-trainings.html'),
('autocad',3,'https://www.tertiarycourses.com.gh/autodesk-autocad-trainings.html'),
('azure ai',3,'https://www.tertiarycourses.com.gh/azure-cloud-computing-courses.html'),
('blockchain',3,'https://www.tertiarycourses.com.gh/blockchain-courses.html'),
('chatbot',3,'https://www.tertiarycourses.com.gh/chatbot-html.html'),
('ChatGPT',3,'https://www.tertiarycourses.com.gh/chatgpt-and-generative-ai-courses.html'),
('Civil 3D',3,'https://www.tertiarycourses.com.gh/java-programming-courses.html'),
('cryptocurrencies',3,'https://www.tertiarycourses.com.gh/cryptocurrencies-courses.html'),
('ethereum',3,'https://www.tertiarycourses.com.gh/ethereum-skillsfuture-courses-in.html'),
('ethereum smart',3,'https://www.tertiarycourses.com.gh/ethereum-skillsfuture-courses-in.html'),
('excel',3,'https://www.tertiarycourses.com.gh/microsoft-excel-trainings.html'),
('finance',3,'https://www.tertiarycourses.com.gh/wsq-finance-courses.html'),
('fusion 360',3,'https://www.tertiarycourses.com.gh/autodesk-fusion-360-trainings.html'),
('ga4',3,'https://www.tertiarycourses.com.gh/google-analytics-courses.html'),
('google analytics',3,'https://www.tertiarycourses.com.gh/google-analytics-courses.html'),
('google workspace',3,'https://www.tertiarycourses.com.gh/google-g-suite-trainings.html'),
('HTML',3,'https://www.tertiarycourses.com.gh/html-css-training-courses.html'),
('illustrator',3,'https://www.tertiarycourses.com.gh/adobe-illustrator-courses.html'),
('iot',3,'https://www.tertiarycourses.com.gh/internet-of-things-iot-training-in.html'),
('iso',3,'https://www.tertiarycourses.com.gh/iso-standards-courses.html'),
('java',3,'https://www.tertiarycourses.com.gh/java-programming-courses.html'),
('Javascript',3,'https://www.tertiarycourses.com.gh/javascript-training-courses-in.html'),
('LinkedIn',3,'https://www.tertiarycourses.com.gh/linkedin-social-media-marketing-courses.html'),
('machine learning',3,'https://www.tertiarycourses.com.gh/machine-learning-courses.html'),
('manufacturing',3,'https://www.tertiarycourses.com.gh/logistics-and-manufacturing-courses.html'),
('Microsoft power BI',3,'https://www.tertiarycourses.com.gh/microsoft-power-platform-software-training-courses.html'),
('neural network',3,'https://www.tertiarycourses.com.gh/network-securities-courses.html'),
('odoo basic accounting',3,'https://www.tertiarycourses.com.gh/accounting-software-training.html'),
('Office tools',3,'https://www.tertiarycourses.com.gh/microsoft-software-training.html'),
('Photoshop',3,'https://www.tertiarycourses.com.gh/adobe-photoshop-courses.html'),
('Photoshop courses',3,'https://www.tertiarycourses.com.gh/adobe-photoshop-courses.html'),
('power automate',3,'https://www.tertiarycourses.com.gh/power-automate-software-training.html'),
('Power BI',3,'https://www.tertiarycourses.com.gh/power-automate-software-training.html'),
('power virtual agent',3,'https://www.tertiarycourses.com.gh/power-automate-software-training.html'),
('problem solving',3,'https://www.tertiarycourses.com.gh/thinking-critically-critical-core-skills-courses.html'),
('quantam physics',3,'https://www.tertiarycourses.com.gh/wsq-quantum-computing-courses.html'),
('quantum',3,'https://www.tertiarycourses.com.gh/wsq-quantum-computing-courses.html'),
('quantum computing',3,'https://www.tertiarycourses.com.gh/wsq-quantum-computing-courses.html'),
('R programming',3,'https://www.tertiarycourses.com.gh/programming-courses.html'),
('raspberry pi',3,'https://www.tertiarycourses.com.gh/raspberry-pi-courses-in.html'),
('Ros 2 Python',3,'https://www.tertiarycourses.com.gh/python-programming.html'),
('smart contract',3,'https://www.tertiarycourses.com.gh/smart-contract-courses.html'),
('smat contract',3,'https://www.tertiarycourses.com.gh/smart-contract-courses.html'),
('sql',3,'https://www.tertiarycourses.com.gh/relational-sql-databases.html'),
('tableau',3,'https://www.tertiarycourses.com.gh/tableau-software-courses.html'),
('time series forecasting in R',3,'https://www.tertiarycourses.com.gh/jobs.html'),
('time series forecasting R',3,'https://www.tertiarycourses.com.gh/jobs.html'),
('Video editing',3,'https://www.tertiarycourses.com.gh/video-editing-for-kids.html'),
('web api',3,'https://www.tertiarycourses.com.gh/web-design-courses.html'),
('Website',3,'https://www.tertiarycourses.com.gh/website-feedback.html'),
('Website development',3,'https://www.tertiarycourses.com.gh/web-design-courses.html'),
('Wordpress',3,'https://www.tertiarycourses.com.gh/wordpress-web-deisgn.html'),
('aws',5,'https://www.tertiarycourses.bt/aws-certification-preparation-exam-courses.html'),
('How to Setup a Successful Online Store',5,'https://www.tertiarycourses.bt/shpify-online-store-training.html'),
('neo4j',5,'https://www.tertiarycourses.bt/graph-database-courses.html');

-- Only set a redirect where the term has none yet (don't overwrite 189 restores
-- or any manually-curated redirect).
UPDATE catalogsearch_query q
  JOIN _sensible_redirects r
    ON q.query_text = r.query_text AND q.store_id = r.store_id
  SET q.redirect = r.redirect
  WHERE q.redirect IS NULL OR q.redirect = '';

INSERT INTO catalogsearch_query
  (query_text, store_id, redirect, is_active, display_in_terms, popularity, num_results)
SELECT r.query_text, r.store_id, r.redirect, 1, 1, 0, 0
FROM _sensible_redirects r
LEFT JOIN catalogsearch_query q
  ON q.query_text = r.query_text AND q.store_id = r.store_id
WHERE q.query_id IS NULL;

DROP TEMPORARY TABLE IF EXISTS _sensible_redirects;
