<?php
/**
 * Production-sourced generator for the CompTIA Exam Voucher migration.
 *
 * Scrapes each CompTIA product page from tertiarycourses.com.sg (the
 * single source of truth that still carries the "Exam Voucher" section
 * inside short_description), extracts that section, and emits SQL that:
 *
 *   1. Appends the extracted HTML to the per-product additional_note
 *      admin-scope row (store_id=0), guarded by NOT LIKE so re-runs
 *      no-op. If no admin-scope row exists yet, INSERTs one.
 *   2. Removes the Exam Voucher section from EVERY store-scoped
 *      short_description row using MySQL REPLACE() on the exact
 *      substring captured from prod. REPLACE is a safe no-op on
 *      rows where the substring has already been stripped.
 *
 * Idempotent. Safe on prod and on already-migrated local DBs.
 *
 * Run inside the web container:
 *   docker exec ai-mms-web-1 php /var/www/html/scripts/local-dev/generate-comptia-exam-voucher-migration.php \
 *     > migrations/152-comptia-exam-voucher-to-additional-note.sql
 */

require_once __DIR__ . '/../../app/Mage.php';
Mage::app('admin');

$conn = Mage::getSingleton('core/resource')->getConnection('core_read');

$attrShort   = (int) $conn->fetchOne("SELECT attribute_id FROM eav_attribute WHERE attribute_code='short_description' AND entity_type_id=4");
$attrAddNote = (int) $conn->fetchOne("SELECT attribute_id FROM eav_attribute WHERE attribute_code='additional_note' AND entity_type_id=4");

$rows = $conn->fetchAll(
    "SELECT p.entity_id, p.sku, uk.value AS url_key"
    . " FROM catalog_product_entity p"
    . " JOIN catalog_product_entity_varchar nm ON nm.entity_id=p.entity_id"
    . "   AND nm.attribute_id=(SELECT attribute_id FROM eav_attribute WHERE attribute_code='name' AND entity_type_id=4)"
    . "   AND nm.store_id=0"
    . " JOIN catalog_product_entity_varchar uk ON uk.entity_id=p.entity_id"
    . "   AND uk.attribute_id=(SELECT attribute_id FROM eav_attribute WHERE attribute_code='url_key' AND entity_type_id=4)"
    . "   AND uk.store_id=0"
    . " WHERE nm.value LIKE '%CompTIA%' ORDER BY p.entity_id"
);

$out = [];
$out[] = "-- Migration 152: move 'Exam Voucher' section from short_description";
$out[] = "-- into additional_note for every CompTIA course that carries it.";
$out[] = "--";
$out[] = "-- Generated by scripts/local-dev/generate-comptia-exam-voucher-migration.php";
$out[] = "-- (scrapes tertiarycourses.com.sg as the source of truth).";
$out[] = "--";
$out[] = "-- Idempotency:";
$out[] = "--   additional_note: UPDATE guarded by NOT LIKE '%Exam Voucher%' so a";
$out[] = "--     re-run on an already-merged value is a no-op. If no admin-scope";
$out[] = "--     row exists, INSERT one.";
$out[] = "--   short_description: REPLACE(value, '<scraped voucher block>', '')";
$out[] = "--     no-ops on rows where the block has already been stripped.";
$out[] = "--";
$out[] = "-- Side effect: fixes the well-known 'Autodesk Exam Voucher' copy-paste";
$out[] = "-- bug to 'CompTIA Exam Voucher' in the migrated copy.";
$out[] = "";

$ctx = stream_context_create(['http' => ['timeout' => 15, 'user_agent' => 'mms-migrator/1.0']]);
$stats = ['ok' => 0, 'no_section' => 0, 'fetch_fail' => 0];

foreach ($rows as $row) {
    $sku    = $row['sku'];
    $urlKey = $row['url_key'];
    $eid    = (int) $row['entity_id'];
    if ($urlKey === '') continue;

    $url  = 'https://www.tertiarycourses.com.sg/' . $urlKey . '.html';
    $html = @file_get_contents($url, false, $ctx);
    if ($html === false) { $stats['fetch_fail']++; fwrite(STDERR, "fetch fail: {$sku}\n"); continue; }

    // Extract the short-description container.
    if (!preg_match('#<div class="short-description">.*?<div class="std"[^>]*>(.*?)</div>\s*</div>#siu', $html, $sd)) {
        fwrite(STDERR, "no short-desc div: {$sku}\n");
        continue;
    }
    $sdInner = $sd[1];

    // Match the Exam Voucher block — h2 + everything up to the next h1/h2
    // or end of container. The leading optional empty <p></p> is included
    // so REPLACE() also drops the typical preceding blank paragraph.
    $pattern = '#(?:<p>\s*</p>\s*)*<h2[^>]*>\s*Exam\s+Voucher\s*</h2>.*?(?=<h[12]\b|\z)#siu';
    if (!preg_match($pattern, $sdInner, $m)) { $stats['no_section']++; continue; }

    $voucherBlock = $m[0];   // exact substring to REPLACE() out
    // Body (everything after the </h2>) is what goes into additional_note.
    if (!preg_match('#<h2[^>]*>\s*Exam\s+Voucher\s*</h2>(.*?)(?=<h[12]\b|\z)#siu', $voucherBlock, $bm)) continue;
    $body = trim($bm[1]);
    // Strip leading/trailing empty <p></p>.
    $body = preg_replace('#^(?:<p>(?:\s|&nbsp;)*</p>\s*)+#i', '', $body);
    $body = preg_replace('#(?:<p>(?:\s|&nbsp;)*</p>\s*)+$#i', '', $body);
    $body = trim($body);
    // Fix copy-paste bug.
    $body = preg_replace('/\bAutodesk\s+Exam\s+Voucher\b/', 'CompTIA Exam Voucher', $body);

    $qBody         = $conn->quote($body);
    $qVoucherBlock = $conn->quote($voucherBlock);
    $qNote2x       = $conn->quote("\n\n" . $body);

    $out[] = "-- {$sku} (entity_id={$eid})";

    // 1) additional_note: append voucher body if not already present.
    $out[] = "UPDATE catalog_product_entity_text"
           . " SET value = CONCAT(value, {$qNote2x})"
           . " WHERE entity_id = {$eid}"
           . " AND attribute_id = {$attrAddNote}"
           . " AND store_id = 0"
           . " AND value NOT LIKE '%Exam Voucher%'"
           . " AND value NOT LIKE '%exam voucher%';";

    // If no admin-scope additional_note row exists yet, create one.
    $out[] = "INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value)"
           . " SELECT 4, {$attrAddNote}, 0, {$eid}, {$qBody} FROM DUAL"
           . " WHERE NOT EXISTS ("
           . "   SELECT 1 FROM catalog_product_entity_text"
           . "    WHERE entity_id = {$eid} AND attribute_id = {$attrAddNote} AND store_id = 0"
           . " );";

    // 2) short_description: strip the voucher block from every store-scoped row.
    $out[] = "UPDATE catalog_product_entity_text"
           . " SET value = REPLACE(value, {$qVoucherBlock}, '')"
           . " WHERE entity_id = {$eid}"
           . " AND attribute_id = {$attrShort};";

    $out[] = "";
    $stats['ok']++;
}

fwrite(STDERR, "Stats: " . json_encode($stats) . "\n");
echo implode("\n", $out);
