<?php
/**
 * Production-sourced generator for the CompTIA Pearson-Vue migration.
 *
 * Scrapes each CompTIA product page from tertiarycourses.com.sg (the
 * single source of truth for short_description that still carries the
 * "Certification Exam at Pearson Vue" section), extracts that section,
 * and emits SQL that:
 *
 *   1. Appends the extracted HTML to the per-course cms_block
 *      `course_<sku>_certification` (UPDATE if exists, INSERT otherwise —
 *      cms_block.identifier has NO unique index on this schema, so
 *      INSERT...ON DUPLICATE KEY UPDATE would silently double-create).
 *   2. Strips the section from every store-scoped short_description row,
 *      MD5-guarded against the CURRENT prod value. On prod this strips
 *      cleanly; on a local DB that's already been stripped (the guard
 *      won't match) the UPDATE is a safe no-op.
 *
 * Run inside the web container:
 *   docker exec ai-mms-web-1 php /var/www/html/scripts/local-dev/generate-comptia-cert-migration-from-prod.php \
 *     > migrations/151-comptia-cert-pearson-vue-to-block.sql
 */

require_once __DIR__ . '/../../app/Mage.php';
Mage::app('admin');

$conn = Mage::getSingleton('core/resource')->getConnection('core_read');

// CompTIA products + their url_keys.
$rows = $conn->fetchAll(
    "SELECT p.entity_id, p.sku, uk.value AS url_key"
    . " FROM catalog_product_entity p"
    . " JOIN catalog_product_entity_varchar nm"
    . "   ON nm.entity_id = p.entity_id"
    . "   AND nm.attribute_id = (SELECT attribute_id FROM eav_attribute"
    . "                          WHERE attribute_code = 'name'"
    . "                            AND entity_type_id = 4)"
    . "   AND nm.store_id = 0"
    . " JOIN catalog_product_entity_varchar uk"
    . "   ON uk.entity_id = p.entity_id"
    . "   AND uk.attribute_id = (SELECT attribute_id FROM eav_attribute"
    . "                          WHERE attribute_code = 'url_key'"
    . "                            AND entity_type_id = 4)"
    . "   AND uk.store_id = 0"
    . " WHERE nm.value LIKE '%CompTIA%'"
    . " ORDER BY p.entity_id"
);

$attrId = (int) $conn->fetchOne(
    "SELECT attribute_id FROM eav_attribute"
    . " WHERE attribute_code = 'short_description' AND entity_type_id = 4"
);

$out = [];
$out[] = "-- Migration 151: move 'Certification Exam at Pearson Vue' from";
$out[] = "-- short_description into the per-course `course_<sku>_certification`";
$out[] = "-- cms_block for every CompTIA course that carries it.";
$out[] = "--";
$out[] = "-- Generated by scripts/local-dev/generate-comptia-cert-migration-from-prod.php";
$out[] = "-- (scrapes tertiarycourses.com.sg as the source of truth).";
$out[] = "--";
$out[] = "-- cms_block.identifier has NO unique index on this schema, so we";
$out[] = "-- use a 2-step upsert (UPDATE first, INSERT if not exists) instead";
$out[] = "-- of INSERT...ON DUPLICATE KEY UPDATE — the latter would silently";
$out[] = "-- create duplicates that confuse the cms_block loader.";
$out[] = "--";
$out[] = "-- short_description UPDATEs are MD5-guarded against the prod value";
$out[] = "-- captured at generation time. Safe to re-run; on a DB whose";
$out[] = "-- short_description has diverged from prod the UPDATE no-ops.";
$out[] = "";

// Marker patterns: scraped HTML has the section as
// <h2>Certification Exam at Pearson Vue</h2><p>...</p> followed by either
// another <h2>/<h1>/<h3> or the end of the short-description container.
// We'll capture from the rendered page's `.short-description .std` block.
$pattern = '#<h2[^>]*>\s*Certification Exam at Pearson Vue\s*</h2>(.*?)(?=<h[123]\b|$)#siu';

$ctx = stream_context_create(['http' => ['timeout' => 15, 'user_agent' => 'mms-migrator/1.0']]);
$skuStats = ['ok' => 0, 'no_match' => 0, 'fetch_fail' => 0, 'skipped' => 0];

foreach ($rows as $row) {
    $sku    = $row['sku'];
    $urlKey = $row['url_key'];
    $eid    = (int) $row['entity_id'];

    if ($urlKey === '') { $skuStats['skipped']++; continue; }
    $url = 'https://www.tertiarycourses.com.sg/' . $urlKey . '.html';

    $html = @file_get_contents($url, false, $ctx);
    if ($html === false) { $skuStats['fetch_fail']++; fwrite(STDERR, "fetch fail: {$sku} {$url}\n"); continue; }

    // Pull the short-description std container.
    if (!preg_match('#<div class="short-description">.*?<div class="std"[^>]*>(.*?)</div>\s*</div>#siu', $html, $sdMatch)) {
        $skuStats['no_match']++; fwrite(STDERR, "no short-desc div: {$sku}\n"); continue;
    }
    $shortDescHtml = $sdMatch[1];

    if (!preg_match($pattern, $shortDescHtml, $m)) {
        $skuStats['no_match']++; fwrite(STDERR, "no pearson section: {$sku}\n"); continue;
    }

    // Extracted HTML wrapped as bold paragraph so it doesn't compete with
    // the Certification card's own h3 header.
    $extracted = '<p><strong>Certification Exam at Pearson Vue</strong></p>'
               . trim($m[1]);

    // Existing block content (local DB read — same content as prod since
    // migration 143 set per-course certification blocks identically).
    $existing = (string) $conn->fetchOne(
        "SELECT content FROM cms_block WHERE identifier = ? ORDER BY block_id LIMIT 1",
        ['course_' . $sku . '_certification']
    );
    $combined = $existing;
    if (strpos($existing, 'Certification Exam at Pearson Vue') === false) {
        $combined = trim($existing . ($existing !== '' ? "\n" : '') . $extracted);
    }

    $identifier = 'course_' . $sku . '_certification';
    $title      = 'Certification — ' . $sku;
    $qIdent     = $conn->quote($identifier);
    $qTitle     = $conn->quote($title);
    $qContent   = $conn->quote($combined);

    // For each store-scoped short_description row that we can reach via
    // prod data, generate the strip UPDATE. Prod has store_id=0 + store_id=1
    // for SG; we MD5-guard against whatever the prod default-scope row is.
    // Since we only scrape the SG default-store URL, use that as the
    // canonical "current" value and apply the same UPDATE to every local
    // store_id row that matches by MD5 — produces the right result on prod
    // (where local mirrors prod) and no-ops elsewhere.
    $allRows = $conn->fetchAll(
        "SELECT store_id, value FROM catalog_product_entity_text"
        . " WHERE entity_id = ? AND attribute_id = ?",
        [$eid, $attrId]
    );

    $out[] = "-- " . $sku . " (entity_id=" . $eid . ", " . count($allRows) . " store row(s))";

    $out[] = "UPDATE cms_block SET content = " . $qContent . ", update_time = NOW()"
           . " WHERE identifier = " . $qIdent . ";";
    $out[] = "INSERT INTO cms_block (title, identifier, content, is_active, creation_time, update_time)"
           . " SELECT " . $qTitle . ", " . $qIdent . ", " . $qContent . ", 1, NOW(), NOW() FROM DUAL"
           . " WHERE NOT EXISTS (SELECT 1 FROM cms_block c WHERE c.identifier = " . $qIdent . ");";
    $out[] = "INSERT IGNORE INTO cms_block_store (block_id, store_id)"
           . " SELECT block_id, 0 FROM cms_block WHERE identifier = " . $qIdent . ";";

    foreach ($allRows as $r) {
        $desc = $r['value'];
        $sid  = (int) $r['store_id'];
        if (strpos($desc, 'Certification Exam at Pearson Vue') === false) {
            continue; // already stripped in this scope
        }
        if (!preg_match($pattern, $desc, $mr, PREG_OFFSET_CAPTURE)) {
            continue;
        }
        $startPos = $mr[0][1];
        $afterEnd = $startPos + strlen($mr[0][0]);
        $newDesc  = substr($desc, 0, $startPos) . substr($desc, $afterEnd);
        $newDesc  = preg_replace('#(?:<p>\s*(?:&nbsp;|\s)*</p>\s*){2,}#siu', '<p>&nbsp;</p>', $newDesc);
        $newDesc  = preg_replace('#\n{3,}#', "\n\n", $newDesc);

        $qNewDesc = $conn->quote($newDesc);
        $qMd5     = $conn->quote(md5($desc));

        $out[] = "UPDATE catalog_product_entity_text t"
               . " JOIN eav_attribute a ON a.attribute_id = t.attribute_id"
               . " SET t.value = " . $qNewDesc
               . " WHERE t.entity_id = " . $eid
               . "   AND t.store_id = " . $sid
               . "   AND a.attribute_code = 'short_description'"
               . "   AND MD5(t.value) = " . $qMd5 . ";";
    }

    $out[] = "";
    $skuStats['ok']++;
}

fwrite(STDERR, "Stats: " . json_encode($skuStats) . "\n");
echo implode("\n", $out);
